- .gitignore
- app.js
- index.html
- package.json
- src/boot.ts
- src/main-app.component.ts
- src/tsconfig.json
- typings.json
- webpack.config.js
It adds a new menu item (Keymaps-ng2) which shows an angular2 component. This will be the starting point to the Keymaps component written in ng2.
> Angular2 initial support

- config-serializer/Serializable.ts
- config-serializer/UhkBuffer.ts
- config-serializer/config-items/KeyMap.ts
- config-serializer/config-items/Macro.ts
- config-serializer/config-items/SwitchLayerAction.ts
based on comment in #30
and because its probably a good idea
> use full byte for each bool

- .gitignore
- index.html
- package.json
- sass/style.scss
- src/components/popover/tab/keymap-tab.component.scss
- src/components/popover/tab/keymap-tab.component.ts
- src/components/popover/tab/keypress-tab.component.scss
- src/components/popover/tab/keypress-tab.component.ts
- src/components/popover/tab/layer-tab.component.scss
- src/components/popover/tab/layer-tab.component.ts
- src/components/popover/tab/longPress.json
- src/components/popover/tab/macro-tab.component.scss
- src/components/popover/tab/macro-tab.component.ts
- src/components/popover/tab/mouse-tab.component.ts
- src/components/popover/tab/scancodes.json
- typings.json
Implementation of select2 wrapper into the Popover, tab Keypress (#45).
@fjozsef and @mondalaci please review the code and give a feedback. Thank you
> Implementation of Select2 wrapper into Popover

- package.json
- src/components/popover/tab/keymap/keymap-tab.component.html
- src/components/popover/tab/keymap/keymap-tab.component.ts
- src/components/popover/tab/keypress/keypress-tab.component.html
- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/components/popover/tab/layer/layer-tab.component.html
- src/components/popover/tab/layer/layer-tab.component.ts
- src/components/popover/tab/macro/macro-tab.component.html
- src/components/popover/tab/macro/macro-tab.component.ts
Updated ng2-select2 to version 0.4.2.
> Update of select2

- src/components/layers/layers.component.html
- src/components/layers/layers.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
> refactor: Layers

- src/components/side-menu/side-menu.component.html
- src/components/side-menu/side-menu.component.scss
- src/components/side-menu/side-menu.component.ts
Improved animation of the side menu. Before we were limited to 200px height. Now animation is handled by angular, so there is no more limits. Also class toggling is now done with Renderer as dictated in style guides.
> Side menu animation

- package.json
- src/components/macro/macro.component.html
Just needed moving some attributes to another line. Updated dragula version in the same process.
> Fix macro sorting

- src/components/macro/macro-item/macro-item.component.scss
- src/components/macro/macro.component.scss
Fixes #104. Take two, had to recreate my repo to get this to work properly.
> Improve macro sorting visuals

- src/components/macro/macro.component.html
- src/components/macro/macro.component.ts
Fixes #106. Seems to work just fine like that.
> Allow sorting while editing macro action

- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/components/popover/tab/layer/layer-tab.component.ts
- src/components/popover/tab/macro/macro-tab.component.ts
- src/components/popover/tab/mouse/mouse-tab.component.ts
- src/components/popover/tab/none/none-tab.component.ts
- src/components/popover/tab/tab.ts
- src/components/svg/keyboard/svg-keyboard.component.ts
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- src/components/svg/keys/svg-switch-keymap-key/svg-switch-keymap-key.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
- src/config-serializer/ClassArray.ts
- src/config-serializer/Serializable.ts
- src/config-serializer/config-items/Keymaps.ts
- src/config-serializer/config-items/Macro.ts
- src/config-serializer/config-items/Macros.ts
- src/config-serializer/config-items/ModuleConfiguration.ts
- src/config-serializer/config-items/ModuleConfigurations.ts
- src/config-serializer/config-items/key-action/KeyAction.ts
- src/config-serializer/config-items/key-action/NoneAction.ts
- src/config-serializer/config-items/macro-action/DelayMacroAction.ts
- src/config-serializer/config-items/macro-action/KeyMacroAction.ts
- src/config-serializer/config-items/macro-action/MacroAction.ts
- src/config-serializer/config-items/macro-action/MoveMouseMacroAction.ts
- src/config-serializer/config-items/macro-action/ScrollMouseMacroAction.ts
- src/config-serializer/config-items/macro-action/TextMacroAction.ts
- src/directives/contenteditable/contenteditable.directive.ts
- src/main-app/main-app.component.ts
- src/services/data-provider.service.ts
- src/services/uhk-configuration.service.ts
- usb/UhkConnection.js
> Added spaces to imports

- src/components/keymap/header/keymap-header.component.scss
- src/components/macro/macro-action-editor/macro-action-editor.component.scss
- src/components/macro/macro.component.scss
- src/components/popover/tab/mouse/mouse-tab.component.scss
- src/components/popover/widgets/icon/icon.component.scss
- src/main-app/global-styles.scss
> Fixed color

- src/app.module.ts
- src/components/add-on/add-on.component.html
- src/components/add-on/add-on.component.ts
- src/components/add-on/add-on.routes.ts
- src/components/add-on/index.ts
- src/components/macro/add/macro-add.component.html
- src/components/macro/add/macro-add.component.ts
- src/components/macro/index.ts
- src/components/macro/macro.routes.ts
- src/components/settings/index.ts
- src/components/settings/settings.component.html
- src/components/settings/settings.component.ts
- src/components/settings/settings.routes.ts
- src/components/side-menu/side-menu.component.html
- src/components/side-menu/side-menu.component.scss
- src/main-app/main-app.routes.ts
> Dummy pages

- src/components/macro/macro.component.ts
> Fixed first macro opening

- src/components/macro/action-editor/macro-action-editor.component.scss
- src/components/macro/action-editor/tab/delay/macro-delay.component.html
- src/components/macro/action-editor/tab/delay/macro-delay.component.ts
- src/components/macro/item/macro-item.component.html
- src/components/macro/item/macro-item.component.scss
- src/components/macro/item/macro-item.component.ts
- src/components/macro/macro.component.html
- src/components/macro/macro.component.scss
- src/components/macro/macro.component.ts
> Macro items toggle

- src/components/side-menu/side-menu.component.html
- src/components/side-menu/side-menu.component.scss
> Menu items highlight

- src/store/effects/macro.ts
> Fixed macro redirect

- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.html
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
> Key action change animation

- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.scss
> Added hover for keys

- src/components/keymap/header/keymap-header.component.html
- src/components/keymap/header/keymap-header.component.ts
- src/components/macro/header/macro-header.component.html
- src/components/macro/header/macro-header.component.ts
> Keymap / Macro name

- src/store/effects/keymap.ts
> Added duplicate redirect

- src/components/popover/tab/mouse/mouse-tab.component.html
- src/components/popover/tab/mouse/mouse-tab.component.scss
- src/main-app/main-app.component.scss
> Mouse speed tab

- src/components/popover/popover.component.ts
- src/components/popover/tab/keymap/keymap-tab.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
> Removed current keymap from switch

- src/components/popover/tab/keymap/keymap-tab.component.html
- src/components/popover/tab/keymap/keymap-tab.component.scss
- src/components/popover/tab/keymap/keymap-tab.component.ts
- src/components/popover/tab/macro/macro-tab.component.html
- src/components/popover/tab/macro/macro-tab.component.scss
- src/components/popover/tab/macro/macro-tab.component.ts
> Remove placeholders in keymap-tab and in macro-tab

- src/components/keymap/header/keymap-header.component.html
- src/components/keymap/header/keymap-header.component.ts
- src/components/side-menu/side-menu.component.html
- src/store/reducers/keymap.ts
> Add default keymap icon hint

- package.json
- src/components/svg/wrap/animation.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
- src/config-serializer/config-items/Layer.ts
> Fix keyboard animation

- src/components/side-menu/side-menu.component.ts
> Sidemenu alphabetic sort

- src/components/add-on/add-on.component.scss
- src/components/add-on/add-on.component.ts
- src/components/keymap/add/keymap-add.component.ts
- src/components/keymap/edit/keymap-edit.component.ts
- src/components/macro/edit/macro-edit.component.scss
- src/components/macro/edit/macro-edit.component.ts
- src/components/settings/settings.component.scss
- src/components/settings/settings.component.ts
- src/main-app/main-app.component.html
> Fix main-app scrollbar

- src/components/keymap/header/keymap-header.component.html
- src/components/keymap/header/keymap-header.component.scss
- src/components/keymap/header/keymap-header.component.ts
> Gray out trash at last keymap instead of not rendering

- src/components/svg/wrap/svg-keyboard-wrap.component.html
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
- src/store/actions/keymap.ts
- src/store/reducers/keymap.ts
I had to downgrade the angular to the latest stable, because there was an error in the animation with the latest beta. (I couldn't find out if the bug is at our side or at their side.)
> Enable OnPush ChangeDetection in SvgKeyboardWrapComponent

- src/store/actions/keymap.ts
- src/store/effects/keymap.ts
- src/store/effects/macro.ts
- src/store/reducers/keymap.ts
PR based on #175.
Currently blocked by #176, because when you delete key action positioning is messed up. When #176 is done, this PR should work correctly.
> Fixed deletion change

- src/app.module.ts
- src/components/macro/edit/macro-edit.component.html
- src/components/macro/edit/macro-edit.component.ts
- src/components/macro/index.ts
- src/components/macro/macro.routes.ts
- src/components/macro/not-found/index.ts
- src/components/macro/not-found/macro-not-found.component.html
- src/components/macro/not-found/macro-not-found.component.scss
- src/components/macro/not-found/macro-not-found.component.ts
- src/store/effects/macro.ts
- src/store/reducers/macro.ts
> No macro text and route update

- src/components/keymap/edit/keymap-edit.component.scss
- src/components/keymap/header/keymap-header.component.scss
- src/components/popover/popover.component.html
- src/components/popover/popover.component.scss
- src/components/popover/popover.component.ts
- src/components/popover/tab/keymap/keymap-tab.component.ts
- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/components/popover/tab/layer/layer-tab.component.ts
- src/components/popover/tab/macro/macro-tab.component.ts
- src/components/popover/tab/mouse/mouse-tab.component.ts
- src/components/popover/tab/none/none-tab.component.ts
- src/components/svg/keyboard/svg-keyboard.component.html
- src/components/svg/keyboard/svg-keyboard.component.ts
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- src/components/svg/module/svg-module.component.html
- src/components/svg/module/svg-module.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
- src/components/svg/wrap/svg-keyboard-wrap.component.scss
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
- src/main-app/main-app.component.scss
> Popover rework

- src/components/popover/tab/keypress/keypress-tab.component.html
- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/components/popover/tab/keypress/scancodes.json
- src/components/popover/tab/layer/layer-tab.component.html
- src/components/popover/tab/layer/layer-tab.component.scss
- src/components/popover/tab/layer/layer-tab.component.ts
- src/main-app/main-app.component.scss
This PR is resolving issue #84.
> Select2 improvements

- src/app.module.ts
- src/components/keyboard/index.ts
- src/components/keyboard/slider/index.ts
- src/components/keyboard/slider/keyboard-slider.component.html
- src/components/keyboard/slider/keyboard-slider.component.scss
- src/components/keyboard/slider/keyboard-slider.component.ts
- src/components/svg/wrap/animation.ts
- src/components/svg/wrap/index.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
- src/components/svg/wrap/svg-keyboard-wrap.component.scss
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
- src/config-serializer/config-items/Layer.ts
> Refactor: extract keyboard-slider

- package.json
- src/components/popover/tab/keypress/keypress-tab.component.html
- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/index.html
> Updated ng2-select2 library, added custom filter

- src/app.module.ts
- src/components/popover/tab/keypress/keypress-tab.component.html
- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.html
- src/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- src/services/capture.service.ts
> Added capture keystroke to the popover

- package.json
> Fixed init value for keypress tab

- src/components/popover/popover.component.ts
- src/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
> Make Esc close popover

- src/components/keyboard/slider/keyboard-slider.component.html
- src/components/keyboard/slider/keyboard-slider.component.ts
- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/components/svg/keyboard/svg-keyboard.component.html
- src/components/svg/keyboard/svg-keyboard.component.ts
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.html
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.scss
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- src/components/svg/module/svg-module.component.html
- src/components/svg/module/svg-module.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
- src/services/mapper.service.ts
> Added capture to keys

- src/components/popover/tab/keymap/keymap-tab.component.ts
- src/components/popover/tab/macro/macro-tab.component.ts
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
- src/components/svg/wrap/svg-keyboard-wrap.component.ts
- src/config-serializer/config-items/Keymap.ts
- src/config-serializer/config-items/Layer.ts
- src/config-serializer/config-items/Module.ts
- src/config-serializer/config-items/UhkConfiguration.ts
- src/config-serializer/config-items/key-action/PlayMacroAction.ts
- src/config-serializer/config-items/key-action/SwitchKeymapAction.ts
- src/config-serializer/config-items/key-action/helper.ts
- src/store/storage/index.ts
Partially reverts e48fdea
@NejcZdovc Review at least the tooltip part.
> Use ids in key actions instead of references

- src/components/macro/header/macro-header.component.ts
- src/store/actions/macro.ts
- src/store/reducers/keymap.ts
- src/store/reducers/macro.ts
Fixes #235 
Rebased on top of #239
> Fixes Keymap remove throw

- src/components/keyboard/slider/keyboard-slider.component.html
- src/components/keyboard/slider/keyboard-slider.component.ts
- src/components/svg/keyboard/svg-keyboard.component.html
- src/components/svg/keyboard/svg-keyboard.component.ts
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- src/components/svg/module/svg-module.component.html
- src/components/svg/module/svg-module.component.ts
- src/components/svg/wrap/svg-keyboard-wrap.component.html
> Removed fast capturing for add keymap page

- src/components/popover/popover.component.html
- src/components/popover/popover.component.ts
- src/components/popover/tab/keymap/keymap-tab.component.ts
- src/components/popover/tab/keypress/keypress-tab.component.ts
- src/components/popover/tab/layer/layer-tab.component.ts
- src/components/popover/tab/macro/macro-tab.component.ts
- src/components/popover/tab/mouse/mouse-tab.component.html
- src/components/popover/tab/mouse/mouse-tab.component.ts
- src/components/popover/tab/none/none-tab.component.ts
- src/components/popover/tab/tab.ts
> Disable button when action is not valid in popover

- src/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- src/services/capture.service.ts
> Added menu key

- package.json
Should be merged after all issues are resolved in this milestone.
> Version 1.0.0-alpha.1

- electron/src/app.module.ts
- electron/src/app/app.component.html
- electron/src/app/app.component.scss
- electron/src/app/app.component.ts
- electron/src/app/app.routes.ts
- electron/src/app/index.ts
- electron/src/components/keymap/keymap.routes.ts
- electron/src/components/missing-device/index.ts
- electron/src/components/missing-device/missing-device.component.html
- electron/src/components/missing-device/missing-device.component.scss
- electron/src/components/missing-device/missing-device.component.ts
- electron/src/index.html
- electron/src/main-app/main-app.component.ts
- electron/src/main-app/main-app.routes.ts
- electron/src/services/uhk-connected.guard.ts
- electron/src/services/uhk-device.service.ts
- shared/src/main-app/main-app.component.scss
- web/src/main-app/main-app.component.scss
> UHK Detection

- shared/src/config-serializer/config-items/Keymap.ts
- shared/src/config-serializer/config-items/Layer.ts
- shared/src/config-serializer/config-items/Module.ts
- shared/src/config-serializer/config-items/key-action/KeyAction.ts
- shared/src/config-serializer/config-items/key-action/SwitchKeymapAction.ts
- shared/src/store/reducers/user-configuration.ts
> Correctly updates new keymap abbrevation in SwitchKeymapActions

- electron/src/app.module.ts
- electron/src/app/app.routes.ts
- electron/src/components/missing-device/missing-device.component.ts
- electron/src/components/privilege-checker/privilege-checker.component.ts
- electron/src/main-app/main-app.component.ts
- electron/src/services/uhk-device-connected.guard.ts
- electron/src/services/uhk-device-disconnected.guard.ts
- electron/src/services/uhk-device-initialized.guard.ts
- electron/src/services/uhk-device-uninitialized.guard.ts
- electron/src/services/uhk-device.service.ts
It makes the redirection work to the privilege screen, if the uhk is connected.
> Redirection accross components based on UHK state

- electron/src/webpack.config.electron-main.js
- electron/src/webpack.config.js
- package.json
- shared/src/components/popover/tab/keypress/keypress-tab.component.ts
- shared/src/components/svg/keyboard/svg-keyboard.component.ts
- shared/src/store/storage/index.ts
- test-serializer/webpack.config.js
- web/src/webpack.config.js
> Update to webpack 2.x

- .travis.yml
> move travis to trusty

- shared/res/presets/QTY.json
- shared/res/presets/VIM.json
- shared/src/components/popover/tab/keypress/keypress-tab.component.html
- shared/src/components/popover/tab/keypress/keypress-tab.component.ts
- shared/src/components/popover/tab/keypress/scancodes.json
- shared/src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- shared/src/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.ts
- shared/src/components/svg/wrap/svg-keyboard-wrap.component.ts
- shared/src/config-serializer/config-items/key-action/KeyAction.ts
- shared/src/config-serializer/config-items/key-action/KeystrokeAction.ts
- shared/src/config-serializer/config-items/key-action/keystroke-type.ts
- shared/src/config-serializer/user-config.json
- shared/src/services/mapper.service.ts
> Media key support

- shared/src/components/popover/tab/keypress/keypress-tab.component.ts
> Fix keystroke selection when additional field is given but no scancode

- shared/src/components/popover/tab/keypress/scancodes.json
- shared/src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- shared/src/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.ts
- shared/src/services/mapper.service.ts
> Additional media keys with icons

- electron/src/app.module.ts
- shared/res/presets/QTY.json
- shared/src/components/svg/keyboard/svg-keyboard.component.html
- shared/src/components/svg/keyboard/svg-keyboard.component.ts
- shared/src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.scss
- shared/src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.model.ts
- shared/src/components/svg/module/svg-module.component.html
- shared/src/components/svg/module/svg-module.model.ts
- shared/src/config-serializer/user-config.json
- shared/src/pipes/index.ts
- shared/src/pipes/safe-style.pipe.ts
- web/src/app.module.ts
> ANSI and ISO layout handling

- shared/src/components/keyboard/slider/keyboard-slider.component.html
- shared/src/components/keyboard/slider/keyboard-slider.component.ts
- shared/src/components/keymap/edit/keymap-edit.component.html
- shared/src/components/keymap/edit/keymap-edit.component.ts
- shared/src/components/svg/keyboard/svg-keyboard.component.html
- shared/src/components/svg/keyboard/svg-keyboard.component.ts
- shared/src/components/svg/wrap/svg-keyboard-wrap.component.html
- shared/src/components/svg/wrap/svg-keyboard-wrap.component.ts
Animation for #137 
It doesn't detect if the uhk is splitted/merged, just animates. Testing with pressing `alt + s`
> Keyboard split/merge animation

- shared/src/store/actions/user-config.ts
- shared/src/store/effects/user-config.ts
- shared/src/store/index.ts
> fix(keymap): Save keymap user configuration after changed

- shared/src/components/layers/layers.component.html
- shared/src/components/layers/layers.component.scss
Based on [bootstrap 3 button group guideline](http://getbootstrap.com/components/#btn-groups).
> use bootstrap button group instead of separate buttons

- shared/src/components/macro/item/macro-item.component.ts
- shared/src/config-serializer/config-items/macro-action/editable-macro-action.ts
- shared/src/config-serializer/config-items/macro-action/key-macro-action.ts
- shared/src/config-serializer/config-items/macro-action/macro-action.ts
- shared/src/config-serializer/user-config.json
> fix: Key macro action saving

- electron/src/app.module.ts
- electron/src/app/app.component.html
- electron/src/components/privilege-checker/privilege-checker.component.ts
- electron/src/services/electron-error-handler.service.ts
- electron/src/services/electron-log.service.ts
- electron/src/services/uhk-device.service.ts
- electron/src/services/uhk-hid-api.service.ts
- electron/src/services/uhk-lib-usb-api.service.ts
- electron/src/store/effects/app.effect.ts
- electron/src/store/reducers/app.reducer.ts
- package.json
- shared/src/main-app/main-app.component.scss
- shared/src/models/angular-notifier-config.ts
- shared/src/models/notification.ts
- shared/src/services/logger.service.ts
- shared/src/store/actions/app.action.ts
- shared/src/store/effects/app.ts
- shared/src/store/effects/auto-update-settings.ts
- shared/src/store/effects/index.ts
- web/src/app.module.ts
- web/src/main-app/main-app.component.html
Add angular-notifier module to show generic notification. This PR use #332 refactoring
> feat(notification): display app errors, close #319

- electron/src/webpack.config.js
- scripts/webpack-helper.js
- web/src/webpack.config.js
Critical dependency: the request of a dependency is an expression
> build(webpack): Fix the request of a dependency is an expression

- shared/src/store/reducers/user-configuration.ts
> Clear key actions without mutating the original layers

- electron/src/app.module.ts
- shared/src/components/keymap/header/keymap-header.component.html
- shared/src/components/macro/header/macro-header.component.html
- shared/src/components/macro/not-found/macro-not-found.component.html
- shared/src/components/uhk-header/uhk-header.html
- shared/src/components/uhk-header/uhk-header.ts
- web/src/app.module.ts
Create a header wrapper component that will contains the undo
notification component. 
Prerequisite of #338
> refactor: Create uhk-header component

- electron/src/app/app.component.html
- electron/src/components/update-available/update-available.component.html
- electron/src/components/update-available/update-available.component.scss
- electron/src/components/update-available/update-available.component.ts
> Hide UpdateAvailableComponent in AppComponent

- shared/src/components/keymap/header/keymap-header.component.ts
- shared/src/store/reducers/user-configuration.ts
> feat(keymap): Keymap abbr should be only number or ASCII char

- shared/src/components/settings/settings.component.html
- shared/src/components/settings/settings.component.ts
- shared/src/components/side-menu/side-menu.component.html
- shared/src/components/side-menu/side-menu.component.ts
- web/src/main-app/main-app.routes.ts
> feat(settings): Only display settings in Agent-electron

- electron/src/services/uhk-hid-api.service.ts
> Detect uhk without async delay

- electron/src/app.module.ts
- electron/src/custom_types/command-line-args.d.ts
- electron/src/electron-main.ts
- electron/src/services/app-renderer.service.ts
- electron/src/store/effects/app.effect.ts
- electron/src/store/index.ts
- package-lock.json
- package.json
- shared/src/components/side-menu/side-menu.component.html
- shared/src/components/side-menu/side-menu.component.ts
- shared/src/models/command-line-args.ts
- shared/src/store/actions/app.action.ts
- shared/src/store/effects/app.ts
- shared/src/store/index.ts
- shared/src/store/reducers/app.reducer.ts
- shared/src/store/reducers/index.ts
- shared/src/util/ipcEvents.ts
> feat(app): Show add-on menu if start app with --addons arg

- shared/src/components/keymap/header/keymap-header.component.html
- shared/src/components/keymap/header/keymap-header.component.ts
- shared/src/components/macro/header/macro-header.component.html
- shared/src/components/popover/tab/keypress/keypress-tab.component.html
- shared/src/components/side-menu/side-menu.component.html
- shared/src/directives/tooltip/tooltip.directive.ts
- shared/src/global-styles.scss
- shared/src/main-app/_tooltip.scss
Close: #364 
Details:
- Refactored the colour definitions of tooltip. Extracted the colours in global-styles
- Add additional properties to the tooltip-directive.
> fix(keymap): Add tooltips to action icons

- shared/src/components/keymap/header/keymap-header.component.html
- shared/src/components/keymap/header/keymap-header.component.ts
- shared/src/components/macro/header/macro-header.component.html
- shared/src/components/macro/header/macro-header.component.ts
- shared/src/store/actions/keymap.ts
- shared/src/store/effects/keymap.ts
- shared/src/store/effects/macro.ts
- shared/src/store/reducers/user-configuration.ts
> fix(keymap): Change keymap name and abbr algorithm

- shared/src/components/popover/tab/keypress/keypress-tab.component.html
> fix(keymap): Fix 'Capture keystroke' button in FF

- shared/src/store/reducers/user-configuration.ts
> Restore renaming keymap call

- shared/src/components/popover/popover.component.ts
- shared/src/components/popover/tab/keymap/keymap-tab.component.ts
> Fixing invalid keymap list propagation

- electron/src/main-app/main-app.component.ts
> Save config on shortcuts

- package-lock.json
- packages/uhk-web/src/app/app.component.scss
- packages/uhk-web/src/app/pages/main-page/main.page.html
- packages/uhk-web/src/app/pages/main-page/main.page.ts
- packages/uhk-web/src/styles.scss
The PR contains 2 things:
- fix a bug not allow scroll vertical on add new keymap button
- when navigate to new route the page scroll up to the screen. It is useful when user at bottom of page and navigate to new section the user will see the top of the page and not the bottom
close #389
> fix(keymap): Add new keymap scrolling

- packages/uhk-web/src/styles.scss
> fix(keymap): Hide horizontal scrollbar

- packages/uhk-agent/package-lock.json
- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/services/app.service.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/services/logger.service.ts
- packages/uhk-agent/src/services/uhk-hid-device.service.ts
- packages/uhk-web/src/renderer/services/electron-log.service.ts
Summary:
- Unified the logging
- Support async/Promise read/write operations
> refactor: Add UhkHidDevice wrapper that unified the USB communication

- packages/uhk-agent/src/services/device.service.ts
- packages/usb/eeprom.js
@mondalaci 
I have 2 question:
- what should do when WriteUserConfig USB command response 2nd byte is not 1
- Should we do anything when WriteUserConfig USB command response 2nd byte is 1 and send the GetKeyboardState USB command
Close: #403
> feat(device): Write user configuration into the eeprom

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix(keymap): Should not automatically capitalize keymap name

- packages/uhk-web/package-lock.json
Simple fresh lock file solved the issue.
> Update npm lock file to fix macro list visibility (closes #425)

- packages/test-serializer/spec/test-serializer.spec.ts
- packages/uhk-common/.gitignore
- packages/uhk-common/index.ts
- packages/uhk-common/jasmine.json
- packages/uhk-common/package-lock.json
- packages/uhk-common/package.json
- packages/uhk-common/src/config-serializer/config-items/key-action/helper.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/keystroke-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/keystroke-action.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/mouse-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/none-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/play-macro-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/switch-keymap-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/switch-keymap-action.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/switch-layer-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/module.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.spec.ts
- packages/uhk-common/src/index.ts
- packages/uhk-common/test/serializer-test-helper.ts
The test coverage is not 100%, but now I have more important tasks so I think I commit it.
@mondalaci if you have time please check my TODO entries and lets discuss about, because I think I found bug(s)
> test(serializer): Add KeystrokeAction tests

- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/store/actions/user-config.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
> fix(user-config): Fix user configuration savings

- packages/uhk-web/src/app/components/device/settings/device-settings.component.html
- packages/uhk-web/src/app/components/device/settings/device-settings.component.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/actions/user-config.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat(device): Reset user configuration on device

- .travis.yml
- package.json
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-usb/src/uhk-hid-device.ts
close: #439 
I can not test it because from the last firmware update I can not connect to the device
> feat(device): Wait for read user/hardware config until device is ready

- .stylelintrc.json
- packages/uhk-web/src/app/app.component.html
- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/app.routes.ts
- packages/uhk-web/src/app/components/uhk-message/uhk-message.component.html
- packages/uhk-web/src/app/components/uhk-message/uhk-message.component.scss
- packages/uhk-web/src/app/components/uhk-message/uhk-message.component.ts
- packages/uhk-web/src/app/pages/loading-page/loading-device.page.ts
- packages/uhk-web/src/app/services/uhk-device-loaded.guard.ts
- packages/uhk-web/src/app/services/uhk-device-loading.guard.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
The loading page visible until the user configuration is not loaded from the device.
related: #296 
close: #431
> feat(agent): Add loading screen

- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/components/device/settings/device-settings.component.html
- packages/uhk-web/src/app/components/device/settings/device-settings.component.ts
- packages/uhk-web/src/styles.scss
> feat(device): Add save config buttons to the Device settings page

- package.json
- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
- packages/uhk-web/src/app/components/device/settings/device-settings.component.html
- packages/uhk-web/src/app/components/device/settings/device-settings.component.ts
- packages/uhk-web/src/app/shared.module.ts
> feat(device): Add confirmation question before reset the configuration

- packages/uhk-web/src/styles.scss
> feat(agent): change header styles

- packages/uhk-common/src/config-serializer/config-items/macro-action/key-macro-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/key-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/mouse-button-macro-action.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/key/macro-key.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/key/macro-key.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/mouse/macro-mouse.component.ts
- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
- packages/uhk-web/src/app/services/user-config.json
- packages/uhk-web/src/styles/common.scss
> refactor: Change name of actions

- .stylelintrc.json
- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.html
- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/macro-action-editor.component.scss
- packages/uhk-web/src/app/components/macro/action-editor/tab/delay/macro-delay.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/delay/macro-delay.component.scss
- packages/uhk-web/src/app/components/macro/action-editor/tab/delay/macro-delay.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/mouse/macro-mouse.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/mouse/macro-mouse.component.scss
- packages/uhk-web/src/app/components/macro/action-editor/tab/mouse/macro-mouse.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.html
- packages/uhk-web/src/app/components/macro/header/macro-header.component.html
- packages/uhk-web/src/app/components/macro/header/macro-header.component.scss
- packages/uhk-web/src/app/components/macro/header/macro-header.component.ts
- packages/uhk-web/src/app/components/macro/item/macro-item.component.scss
- packages/uhk-web/src/app/util/html-helper.ts
- packages/uhk-web/src/app/util/index.ts
> feat(ui): macro ui improvement

- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
> fix(keymap): Secondary role show 'None' value if not set

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix(keymap): Handle more than 35 same keymap abbreviation

- packages/uhk-common/src/config-serializer/config-items/macro-action/keymap.spec.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.spec.ts
- packages/uhk-web/test/user-config-helper.ts
> test(user-config): fix unit tests

- packages/uhk-agent/src/models/queue-entry.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/services/queue-manager.ts
> feat(device): make USB calls sequential

- packages/uhk-usb/src/util.ts
- packages/usb/write-hca.js
> fix(device): use module import in uhk-usb

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-usb/src/models/load-configurations-result.ts
- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-usb/src/util.ts
- packages/usb/write-userconfig.ts
> feat(scripts): Add write-userconfig

- packages/uhk-agent/src/services/app.service.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/services/sudo.service.ts
- packages/uhk-common/src/models/device-connection-state.ts
- packages/uhk-common/src/models/index.ts
- packages/uhk-usb/src/uhk-hid-device.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/app.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> fix(device): check privilege on Linux

- packages/uhk-agent/src/services/sudo.service.ts
- packages/uhk-web/src/app/store/effects/device.ts
> fix(device): use tmp path to run setup-rules.sh

- scripts/release.js
> build: set Apple appId => com.ultimategadgetlabs.agent

- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.ts
> fix(keymap): Don't show keymap description in the key action popover

- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.scss
> feat(popover): Add Non-US help tooltip to popover

- packages/uhk-common/src/config-serializer/config-items/key-action/helper.ts
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
- packages/uhk-web/src/app/components/uhk-header/uhk-header.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> Fix 560 delete bind play macro action when macro delete

- packages/uhk-web/src/app/store/effects/device.ts
> fix(config): Save reset user configuration in web module

- packages/uhk-usb/src/constants.ts
- packages/uhk-usb/src/uhk-operations.ts
> feat(device): Make Agent able to unbrick bricked modules

- CHANGELOG.md
> correction to the current year :)

- package-lock.json
- package.json
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
> feat: enhance device firmware page

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/models/configuration-reply.ts
- packages/uhk-common/src/models/hardware-module-info.ts
- packages/uhk-common/src/models/hardware-modules.ts
- packages/uhk-common/src/models/index.ts
- packages/uhk-usb/src/constants.ts
- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> feat: show firmware version of the device/modules on firmware page

- packages/uhk-agent/src/electron-main.ts
> fix: display agent icon when user use ALT + TAB

- packages/uhk-agent/src/electron-main.ts
> feat: not allow run multiple Agent

- packages/uhk-usb/src/uhk-hid-device.ts
- packages/usb/uhk.js
See: https://github.com/UltimateHackingKeyboard/firmware/pull/112/commits/6f0b1adc14c293c05ecc0c8039b5ca516917e59e
> The usage page and usage number was changed

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/models/ipc-response.ts
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.html
- packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.ts
- packages/uhk-web/src/app/components/xterm/xterm.component.html
- packages/uhk-web/src/app/components/xterm/xterm.component.scss
- packages/uhk-web/src/app/components/xterm/xterm.component.ts
- packages/uhk-web/src/app/models/firmware-upgrade-error.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
- packages/uhk-web/src/app/store/reducers/progress-button-state.ts
- packages/uhk-web/src/styles.scss
> feat: update firmware version after update

- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.html
- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.ts
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/components/file-upload/file-upload.component.html
- packages/uhk-web/src/app/components/file-upload/file-upload.component.ts
- packages/uhk-web/src/app/components/file-upload/index.ts
- packages/uhk-web/src/app/shared.module.ts
close #648 
The component allow upload the same file multiple times
> feat: add file upload component

- packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.html
- packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.ts
- packages/uhk-web/src/app/components/auto-grow-input/index.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
- packages/uhk-web/src/app/components/side-menu/side-menu.component.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/styles.scss
- packages/uhk-web/src/styles/_side-menu.scss
close #601 
I created a `AutoGrowInputComponent` we could use it for
- edit macro action name
- edit keymap abbrevation
remove code duplication
> feat: set disable style of device name in side menu

- packages/uhk-usb/src/uhk-blhost.ts
> fix: blhost wrapper return with Promise.reject if error code !== 0

- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/models/tmp-firmware.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/util/get-package-json-from-path-async.ts
- packages/uhk-agent/src/util/index.ts
- packages/uhk-agent/src/util/save-extract-firmware.ts
> feat: log firmware version before upgrading firmware

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: SwitchKeymapAction not allow to refer to itself

- packages/uhk-agent/src/services/app.service.ts
- packages/uhk-common/src/models/app-start-info.ts
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/store/actions/app.ts
- packages/uhk-web/src/app/store/effects/app.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> feat: Show not supported OS on firmware page when relevant

- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.scss
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.ts
> fix: only animate keyboard separator when splitting

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: only flash the remapped key

- packages/uhk-web/src/styles/uhk-icons/uhk-icon.scss
> feat: change side menu Agent icon

- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> feat: Tweak unsupported Windows firmware update notification

- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
> feat: keep current selected layer when changing keymap

- packages/uhk-web/src/app/app.component.html
- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.html
- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.ts
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/module/svg-module.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/models/svg-key-events.ts
> feat: add save to keyboard and remap shortcut keys

- packages/uhk-web/src/app/components/agent/about/about.component.html
- packages/uhk-web/src/app/components/agent/about/about.component.ts
- packages/uhk-web/src/app/components/agent/agent.routes.ts
- packages/uhk-web/src/app/components/agent/help-page/help-page.component.html
- packages/uhk-web/src/app/components/agent/help-page/help-page.component.scss
- packages/uhk-web/src/app/components/agent/help-page/help-page.component.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/directives/external-url/external-url.directive.ts
- packages/uhk-web/src/app/directives/external-url/index.ts
- packages/uhk-web/src/app/directives/index.ts
- packages/uhk-web/src/app/pages/help-page/help.page.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/styles.scss
close #717 
Created the `externalUrl` directive than encapsulating the browser/electron link opening function. Just simple add to an `a` HTML element
> feat: add help page

- packages/uhk-web/src/app/components/macro/item/macro-item.component.html
> fix: no scroll when macro tab selected on popover

- packages/usb/get-variable.js
- packages/usb/set-variable.js
- packages/usb/uhk.js
> Add scripts for getting/setting firmware variables

- package-lock.json
- package.json
> chore: upgrade electron builder => 20.26.0

- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/models/remap-info.ts
> fix: uncheck 'Remap on all keyboard' and 'Remap on all layer' checkbox by default

- package-lock.json
- package.json
it is fix "Unknown CSS word" error in IntelliJ
> chore: upgrade stylelint => 9.5.0

- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
- packages/uhk-web/src/app/components/keymap/add/keymap-add.component.ts
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- packages/uhk-web/src/app/components/popover/widgets/icon/icon.component.ts
- packages/uhk-web/src/app/components/svg/module/svg-module.component.ts
- packages/uhk-web/src/styles/_ngx-select-ex.scss
> fix: use OnPush change detection on the keymap edit and add pages

- packages/uhk-web/src/app/components/svg/constants.ts
- packages/uhk-web/src/app/components/svg/keys/index.ts
- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-one-line-text-key/svg-one-line-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-one-line-text-key/svg-one-line-text-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-secondary-role/index.ts
- packages/uhk-web/src/app/components/svg/keys/svg-secondary-role/svg-secondary-role.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-secondary-role/svg-secondary-role.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-single-icon-key/svg-single-icon-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-single-icon-key/svg-single-icon-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-text-icon-key/svg-text-icon-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-text-icon-key/svg-text-icon-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-two-line-text-key/svg-two-line-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-two-line-text-key/svg-two-line-text-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/util.ts
- packages/uhk-web/src/app/services/mapper.service.ts
- packages/uhk-web/src/app/shared.module.ts
> feat: secondary role visualisation

- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
- packages/uhk-web/src/app/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/models/key-modifier-model.ts
- packages/uhk-web/src/app/models/svg-key-events.ts
- packages/uhk-web/src/app/services/capture.service.ts
- packages/uhk-web/src/app/services/mapper.service.ts
- packages/uhk-web/src/app/util/index.ts
- packages/uhk-web/src/app/util/key-modifier-model-mapper.ts
> fix: key modifier reordering

- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.scss
> fix: modifier button layout

- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
> fix: Alt+Tab triggers "Remap on all layers"

- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.scss
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
- packages/uhk-web/src/app/components/popover/tab/tab.ts
> feat: remap on all keymap warning

- packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.scss
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
> feat: allow Layer Switcher secondary roles only on base layer

- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.ts
> fix: macro action text overlap

- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/electron-menu.ts
> feat: add "Edit" menu to MacOs build

- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.scss
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/layer/layer-tab.component.ts
> feat: disable other popover tabs if the current key is layer switcher action

- packages/uhk-web/src/app/components/svg/keys/svg-single-icon-key/svg-single-icon-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-single-icon-key/svg-single-icon-key.component.ts
- packages/uhk-web/src/app/services/mapper.service.ts
> feat: use icon for play/pause keypress action

- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/store/actions/app.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
> fix: stop event propagation when capturing keypress action

- packages/uhk-usb/src/uhk-hid-device.ts
> feat: log USB device list before check permission

- packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/directives/cancelable/cancelable.directive.ts
close #643 	
prerequisite of angular upgrade
> fix: user Renderer2 instead of deprecated Renderer

- package-lock.json
- package.json
- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/services/app.service.ts
- packages/uhk-common/src/models/command-line-args.ts
- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
- packages/uhk-web/src/app/util/version-helper.ts
> feat: allow 8.4.3 firmware features

- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
- packages/uhk-web/src/app/services/mapper.service.ts
> feat: show os specific modifiers for macro actions

- packages/uhk-usb/src/uhk-hid-device.ts
> fix: exclude Steam Controller from the devices list

- packages/uhk-agent/package.json
- scripts/rebuild-node-hid.js
Reverts UltimateHackingKeyboard/agent#853
> Revert "chore: rebuild node-hid to hide USB usage data"

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-web/src/app/components/device/device.routes.ts
- packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.html
- packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
> fix: device recovery mode

- packages/uhk-web/src/app/components/svg/module/svg-module.component.html
> fix: Pressing Tab after "update description" corrupts UI (#872)

- packages/uhk-web/src/tsconfig.app.json
- packages/uhk-web/src/tsconfig.renderer.json
1 more step forward to the angular upgrade.
Summary:
- what does it mean: https://blog.ninja-squad.com/2017/09/18/what-is-new-angular-4.4/
Test:
I started the agent in electron mode and I clicked on components but I did not realise any changes in the layout
> chore: set preserveWhitespaces: false in angular tsconfig.json

- package-lock.json
- package.json
fix: https://nodesecurity.io/advisories/658
> chore: upgrade gh-pages => 2.0.1

- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/models/window-state.ts
- packages/uhk-agent/src/util/window.ts
> feat: save window state when closing agent

- packages/uhk-agent/src/services/app-update.service.ts
- packages/uhk-common/src/models/auto-update-settings.ts
- packages/uhk-common/src/models/index.ts
- packages/uhk-web/src/app/app.component.html
- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/components/agent/settings/settings.component.html
- packages/uhk-web/src/app/components/agent/settings/settings.component.ts
- packages/uhk-web/src/app/components/auto-update-settings/auto-update-settings.html
- packages/uhk-web/src/app/components/auto-update-settings/auto-update-settings.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
- packages/uhk-web/src/app/components/update-available/update-available.component.html
- packages/uhk-web/src/app/components/update-available/update-available.component.scss
- packages/uhk-web/src/app/components/update-available/update-available.component.ts
- packages/uhk-web/src/app/models/update-info.ts
- packages/uhk-web/src/app/services/app-update-renderer.service.ts
- packages/uhk-web/src/app/services/datastorage-repository.service.ts
- packages/uhk-web/src/app/store/actions/app-update.action.ts
- packages/uhk-web/src/app/store/actions/auto-update-settings.ts
- packages/uhk-web/src/app/store/effects/app-update.ts
- packages/uhk-web/src/app/store/effects/auto-update-settings.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app-update.reducer.ts
- packages/uhk-web/src/app/store/reducers/auto-update-settings.ts
- packages/uhk-web/src/renderer/services/electron-datastorage-repository.service.ts
- packages/uhk-web/src/styles.scss
- packages/uhk-web/src/styles/_variables.scss
- packages/uhk-web/src/styles/common.scss
> feat: redesign auto-update component

- packages/uhk-web/src/app/store/effects/device.ts
> fix: agent falsely reports UHK detected

- packages/uhk-common/src/models/udev-rules-info.ts
- packages/uhk-usb/src/uhk-hid-device.ts
- packages/uhk-web/src/app/store/reducers/device.ts
For easier log reading better to use string enum.
> feat: convert UdevRulesInfo to string enum

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: delete LayerSwitcher on the dest layer when LayerSwitcher remove/changing

- packages/uhk-usb/src/uhk-hid-device.ts
- rules/50-uhk60_v2.rules
- scripts/release.js
> fix: don't show the udev setup info if udev v2 setup available

- packages/uhk-common/src/config-serializer/config-items/index.ts
- packages/uhk-common/src/config-serializer/config-items/mouse-speed-configuration.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.html
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.scss
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.ts
- packages/uhk-web/src/app/services/default-mouse-speeds.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: Provide reasonable default mouse settings for Macs

- package-lock.json
- package.json
prerequisite of angular 8 upgrade
> chore: upgrade typescript => 3.5.3

- packages/uhk-agent/package.json
> chore: write kboot logs in development mode

- packages/uhk-web/src/app/components/editable-text/editable-text.component.html
> feat: ESC cancel the keymap description editing

- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/components/xterm/xterm.component.ts
> feat: scroll to the end of the firmware log when success of failed panel visible

- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.html
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.html
> fix: confirmation popover titles

- packages/uhk-web/src/app/store/reducers/device.ts
> feat: Make the UHK of the web build split instead of merged

- package.json
- packages/usb/user-config-json-to-bin.ts
usage of the script
`$ npm run convert-user-config-to-bin -- <path of the bin file>`
> chore: add convert-user-config-to-bin npm script

- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/components/agent/help-page/help-page.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
- packages/uhk-web/src/app/models/index.ts
- packages/uhk-web/src/app/models/macro-menu-item.ts
- packages/uhk-web/src/app/models/side-menu-page-state.ts
- packages/uhk-web/src/app/store/actions/app.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
> feat: show macro usage count

- packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.html
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
- packages/uhk-web/src/app/store/actions/macro.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
close #1040 
Also, fix the macro text editing.
> fix: macro reordering and text editing

- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/styles/_ngx-select-ex.scss
> feat: gray out the current keymap in keymap tab dropdown list

- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
- packages/uhk-web/src/app/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.html
- packages/uhk-web/src/app/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/util/key-modifier-model-mapper.ts
> fix: Macro keystroke capture sets all modifiers

- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.scss
> fix: keyboard description z-index

- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.scss
> fix: 1px select2 UI glitch in popover

- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.ts
> feat: Only animate the halves when they get merged or split

- scripts/launcher-script.sh
- scripts/release.js
> chore: use launcher-script in linux appImage distribution package

- packages/uhk-web/src/app/components/agent/help-page/help-page.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
- packages/uhk-web/src/app/models/side-menu-page-state.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
> feat: only display macro counts on hover

- packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.html
- packages/uhk-web/src/styles.scss
> feat: macro text info tooltip

- packages/uhk-usb/src/models/get-device-options.ts
- packages/uhk-usb/src/models/index.ts
- packages/uhk-usb/src/uhk-hid-device.ts
> fix: log entries colors when upgrading firmware.

- packages/uhk-web/src/app/store/effects/app.ts
- packages/uhk-web/src/app/store/effects/device.ts
> fix: Don't jump to default keymap upon state change

- packages/uhk-usb/src/uhk-hid-device.ts
> fix: Devices shouldn't be relisted when unchanged

- packages/uhk-usb/src/uhk-hid-device.ts
- packages/uhk-web/src/app/app.routes.ts
- packages/uhk-web/src/app/components/udev-rules/udev-rules.component.ts
- packages/uhk-web/src/app/services/uhk-device-udev.guard.ts
- packages/uhk-web/src/app/store/effects/device.ts
- rules/50-uhk60.rules
- rules/50-uhk60_v2.rules
- scripts/release.js
> fix: udev rule permissions

- packages/uhk-agent/package-lock.json
- packages/uhk-agent/package.json
- packages/uhk-agent/src/models/tmp-firmware.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/util/get-package-json-from-path-async.ts
- packages/uhk-agent/src/util/index.ts
- packages/uhk-agent/src/util/sanity-check-firmware.ts
- packages/uhk-agent/src/util/save-extract-firmware.ts
> feat: sanity-check firmware files before updates

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/models/config-sizes-info.ts
- packages/uhk-common/src/models/index.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.html
- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.ts
- packages/uhk-web/src/app/components/progressbar/uhk-progress-bar.component.html
- packages/uhk-web/src/app/components/progressbar/uhk-progress-bar.component.scss
- packages/uhk-web/src/app/components/progressbar/uhk-progress-bar.component.ts
- packages/uhk-web/src/app/models/uhk-progress-bar-state.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
- packages/uhk-web/src/styles.scss
> feat: display available on-board storage

- packages/uhk-agent/src/util/window.ts
> fix: GUI not rendering when the window size is too small

- packages/uhk-web/src/app/util/version-helper.ts
Uncaught Error: Cannot find module './functions/gte'
> fix: semver lazy loading

- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/services/app.service.ts
- packages/uhk-agent/src/services/sudo.service.ts
- packages/uhk-agent/src/util/get-udev-file-content-async.ts
- packages/uhk-agent/src/util/index.ts
- packages/uhk-common/src/models/app-start-info.ts
- packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.html
- packages/uhk-web/src/app/components/udev-rules/udev-rules.component.ts
- packages/uhk-web/src/app/models/privilage-page-sate.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
> feat: read udev file content from file

- packages/uhk-agent/src/util/get-udev-file-content-async.ts
> fix: udev file content reading on non Linux platform

- packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.html
> feat: not allow to collapse the user config history panel

- packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.html
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/styles.scss
> feat: tweak user config history

- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.ts
- packages/uhk-web/src/app/store/effects/device.ts
> fix: load user configuration storage sizes when device connected

- rules/50-uhk60.rules
> fix: use GROUP and MODE instead of the TAG in udev file

- packages/uhk-agent/package-lock.json
- packages/uhk-agent/package.json
- packages/uhk-agent/src/custom_types/command-line-usage.d.ts
- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/util/command-line.ts
- packages/uhk-agent/src/util/index.ts
- packages/uhk-common/src/models/command-line-args.ts
- packages/uhk-usb/src/uhk-hid-device.ts
- rules/50-uhk60.rules
close: #1161
`npm run electron -- -- -- --help` show the help in development environment
> feat: '--preserve-udev-rules' command line argument

- packages/uhk-web/src/app/store/index.ts
> fix: "macro playback is not implemented" in web build

- packages/uhk-web/src/app/components/macro/action-editor/tab/mouse/macro-mouse.component.scss
- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
> feat: Macro UI tweaks

- packages/uhk-common/src/models/application-settings.ts
- packages/uhk-web/src/app/components/agent/settings/settings.component.html
- packages/uhk-web/src/app/components/agent/settings/settings.component.ts
- packages/uhk-web/src/app/components/auto-update-settings/auto-update-settings.html
- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.html
- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.ts
- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/store/actions/app.ts
- packages/uhk-web/src/app/store/effects/app.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
- packages/uhk-web/src/styles.scss
> feat: no animation option

- packages/uhk-agent/src/services/device.service.ts
> fix: stop polling before start communicate with the device

- packages/uhk-usb/package-lock.json
- packages/uhk-usb/package.json
- packages/uhk-usb/src/uhk-hid-device.ts
> fix: set udevRulesInfo = OK when Agent runs in privileged context

- packages/uhk-web/src/app/components/linux-privilege-checker/index.ts
- packages/uhk-web/src/app/components/linux-privilege-checker/linux-privilege-checker.component.html
- packages/uhk-web/src/app/components/linux-privilege-checker/linux-privilege-checker.component.scss
- packages/uhk-web/src/app/components/linux-privilege-checker/linux-privilege-checker.component.ts
- packages/uhk-web/src/app/components/mac-privilege-checker/index.ts
- packages/uhk-web/src/app/components/mac-privilege-checker/mac-privilege-checker.component.html
- packages/uhk-web/src/app/components/mac-privilege-checker/mac-privilege-checker.component.scss
- packages/uhk-web/src/app/components/mac-privilege-checker/mac-privilege-checker.component.ts
- packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.html
- packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.scss
- packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> feat: show MacOs privilege error

- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
> fix: hypersensitive to mouse movement in macro editor

- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
> fix: destroy dragula group when destroying component

- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.scss
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
> fix: add new macro item animations

- packages/uhk-web/angular.json
- packages/uhk-web/src/index.html
> fix: favicon location

- packages/uhk-web/src/app/components/popover/tab/layer/layer-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/layer/layer-tab.component.scss
> feat: use ngx-select in layer-tab.component.html

- packages/uhk-web/src/app/components/uhk-header/uhk-header.html
- packages/uhk-web/src/app/components/undoable-notifier/undoable-notifier.component.html
- packages/uhk-web/src/app/components/undoable-notifier/undoable-notifier.component.scss
> feat: undo notification shouldn't affect layout

- packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.html
- packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.scss
- packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.ts
- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.html
- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.scss
- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.ts
- packages/uhk-web/src/app/components/macro/header/macro-header.component.html
- packages/uhk-web/src/app/components/macro/header/macro-header.component.ts
> feat: use the auto-grow-input everywhere

- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
- packages/uhk-web/src/app/components/undoable-notifier/undoable-notifier.component.scss
> fix: default icon position and undo notifier z-index

- .github/workflows/ci.yml
- .travis.yml
- appveyor.yml
- package.json
- scripts/release.js
> ci: release with GitHub Actions

- packages/uhk-web/src/app/store/effects/user-config.ts
related story #678 
Import Buffer from the 'buffer/' package
> fix: import user configuration

- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
> fix: side menu star icon is misplaced

- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.ts
- packages/uhk-web/src/app/store/index.ts
> feat: Allow more character types on the LED display

- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
It hasn't been used in the code.
> chore(web): delete @ngrx/store-log-monitor dependency

- packages/uhk-agent/src/services/app-update.service.ts
> fix: switch off auto download to prevent paralel download

- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
- packages/uhk-web/src/tsconfig.app.json
Summary:
- change the build target to es6
- fix a few immutability issue
> fix: web build

- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.html
- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.scss
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.html
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.scss
Fixes #1279 
I added a divider on the mouse speed page because I felt it made it clearer which side belongs where.
> #1279 Layout improvements

- packages/uhk-web/src/app/components/agent/about/about.component.html
- packages/uhk-web/src/app/components/agent/about/about.component.ts
> feat: add spinner to the about page loading state

- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/models/exchange-keys-action.model.ts
- packages/uhk-web/src/app/models/index.ts
- packages/uhk-web/src/app/services/key-action-drag-and-drop.service.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/actions/keymap.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: drag and drop key actions

- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-text-icon-key/svg-text-icon-key.component.ts
- packages/uhk-web/src/app/services/mapper.service.ts
> feat: add secondary arrow icons to numpad keys

- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.ts
- packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.html
- packages/uhk-web/src/app/models/index.ts
- packages/uhk-web/src/app/models/load-user-configuration-from-file-payload.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/store/actions/user-config.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/reducers/user-configuration-history.reducer.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: decouple Import Configuration from Save To Keyboard

- package-lock.json
> chore: rebuild root package-lock.json

- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.html
- packages/uhk-web/src/app/components/slider-wrapper/slider-wrapper.component.scss
> fix(web): don't wrap white spaces in side-wrapper

- packages/uhk-web/angular.json
> build(uhk-web): switch off circular dependencies warning

- packages/uhk-common/src/config-serializer/config-items/key-action/helper.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/keystroke-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/keystroke-action.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/mouse-action.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/play-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/switch-keymap-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/switch-keymap-action.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/switch-layer-action.spec.ts
- packages/uhk-common/src/config-serializer/config-items/key-action/switch-layer-action.ts
- packages/uhk-common/src/config-serializer/config-items/keymap.ts
- packages/uhk-common/src/config-serializer/config-items/layer.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/delay-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/helper.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/key-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/mouse-button-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/move-mouse-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/scroll-mouse-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro-action/text-macro-action.ts
- packages/uhk-common/src/config-serializer/config-items/macro.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration.ts
- packages/uhk-common/src/config-serializer/config-items/module.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.spec.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
- packages/uhk-common/test/serializer-test-helper.ts
- packages/uhk-web/src/app/store/effects/keymap.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> refactor: user configuration deserializer v1

- .github/workflows/ci.yml
Hard code until the actions/setup-node@v2 wouldn't support it.
It is the fastest solution
> build: hard code the node version in ci.yml

- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/key/macro-key.component.scss
> fix: ui glitches

- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
> fix: side menu collapsed item visibility

- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
> fix: side menu high DPI hover behaviour

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.html
- packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/styles/_global.scss
- packages/uhk-web/src/styles/themes/_light.scss
Summary
- fix the tooltip position of the "Copy to clipboard" 
- auto close recovery page after success recovery
- width of the theme tooltip
- restyle confirmation popovers
> feat: ui improvements

- .github/workflows/deploy-gh-pages.yml
- package-lock.json
- package.json
> ci: auto deploy GitHub Pages

- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.scss
> fix: keyboard description editing

- packages/uhk-agent/src/util/reenumerate-and-exit.ts
- packages/uhk-usb/src/models/index.ts
- packages/uhk-usb/src/models/reenumerate-option.ts
- packages/uhk-usb/src/uhk-hid-device.ts
- packages/uhk-usb/src/uhk-operations.ts
- packages/usb/reenumerate.ts
> refactor: introduce ReenumerateOption

- packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.ts
- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.ts
- packages/uhk-web/src/app/components/macro/header/macro-header.component.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: rename macro/keymap to an existing name

- packages/uhk-web/src/app/components/popover/popover.component.scss
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
> fix: popover state visualization

- packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.ts
> fix: popover switch keymap action setting

- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.scss
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/components/svg/module/svg-module.component.html
- packages/uhk-web/src/app/services/key-action-drag-and-drop.service.ts
> fix: drag and drop of not rectangle keys

- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
> fix: macro editor jump to the bottom of the page after save

- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
> fix: scroll position after macro item drag-and-drop

- packages/uhk-usb/src/uhk-operations.ts
- packages/usb/factory-update.ts
- packages/usb/kboot-firmware-upgrade.ts
- packages/usb/src/error-handler.ts
- packages/usb/src/index.ts
- packages/usb/src/invalid-argument-error.ts
- packages/usb/src/util/get-device-id-from-arg.ts
- packages/usb/src/util/index.ts
- packages/usb/update-firmwares-and-configs.ts
- packages/usb/update-firmwares.ts
- packages/usb/write-hardware-config.ts
> feat: handle device as argument when write hardware config

- packages/uhk-agent/src/services/app.service.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/index.ts
- packages/uhk-common/src/models/update-firmware-data.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-web/src/app/components/device/firmware-file-upload/firmware-file-upload.component.html
- packages/uhk-web/src/app/components/device/firmware-file-upload/firmware-file-upload.component.ts
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.scss
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/models/firmware-upgrade-state.ts
- packages/uhk-web/src/app/models/firmware-upgrade-steps.ts
- packages/uhk-web/src/app/models/index.ts
- packages/uhk-web/src/app/models/update-firmware-with-payload.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
- packages/uhk-web/src/app/store/reducers/firmware-upgrade.reducer.ts
- packages/usb/update-firmwares.ts
- packages/usb/update-module-firmware.ts
> feat: show which keyboard half or module is being firmware-updated

- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-web/src/app/store/reducers/firmware-upgrade.reducer.ts
closes #1490 
Summary:
- wait max 30 sec when trying to connect module after firmware upgrade
- add `.` after the log entry if the next log message equal to the previous
> feat: wait max 30 sec when trying to connect module after firmware upgrade

- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/store/reducers/firmware-upgrade.reducer.ts
> fix: invalid check marks on force update

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.ts
> fix: detect recovery mode

- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
> fix: remove extra closing tag of firmware-file-upload on the firmware upgrade screen

- packages/uhk-web/src/app/store/reducers/device.ts
> feat: show "Searching for your UHK" message until the devices info not loaded

- packages/uhk-agent/package.json
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-usb/src/utils/usb-device-json-formatter.ts
- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/models/firmware-upgrade-state.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/firmware-upgrade.reducer.ts
> feat: module recovery

- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/electron-menu.ts
- packages/uhk-agent/src/util/command-line.ts
- packages/uhk-common/src/models/command-line-args.ts
> feat: --devtools command line argument

- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.html
> fix: misplaced recording dot on keycluster right mouse button

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: delete macro

- packages/uhk-web/src/styles/_tooltip.scss
- packages/uhk-web/src/styles/_variables.scss
https://sass-lang.com/documentation/breaking-changes/slash-div
> chore: use sass:math.div instead of /

- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/util/get-window-background-color.ts
- packages/uhk-agent/src/util/index.ts
> fix: white splashes during application startup

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: macro/keymap name generation when duplicating the item

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: remove SwitchKeymapAction when the keymap not exists at add new keymap

- packages/uhk-web/src/app/components/macro/action-editor/tab/mouse/macro-mouse.component.html
> fix: input field validation of the mouse move and scroll macro action

- packages/uhk-web/src/app/components/popover/widgets/capture-keystroke/capture-keystroke-button.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/services/capture.service.ts
> fix: invalid keypress capturing

- packages/uhk-web/src/app/components/macro/action-editor/macro-action-editor.component.ts
> feat: save macro by CTRL + Enter

- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
> feat: scroll to bottom when new macro item added

- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.ts
> fix: svg icon-text key 2 line text rendering

- package-lock.json
- package.json
- scripts/release.js
> feat: Apple Universal installer

- packages/uhk-web/src/app/components/macro/action-editor/macro-action-editor.component.html
- packages/uhk-web/src/app/components/macro/action-editor/macro-action-editor.component.ts
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
- packages/uhk-web/src/app/components/macro/item/macro-item.component.html
- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
- packages/uhk-web/src/app/store/index.ts
If you would like to test then
- in web module set the `"userConfigVersion": "5.0.0"` in the root `package.json`
- on electron upgrade the firmware that support the `5.0.0` user configuration
> feat: allow macro command if user config version >= 5.0.0

- packages/uhk-web/src/app/components/device/device.routes.ts
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
> feat: rename "Mouse speed" menu item to "Mouse key speed"

- packages/uhk-web/src/app/components/layers/layer-option.component.html
- packages/uhk-web/src/app/components/layers/layer-option.component.ts
> fix: checked state of layer option checkbox

- packages/uhk-web/src/app/app.component.html
- packages/uhk-web/src/app/app.component.scss
- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/app.routes.ts
- packages/uhk-web/src/app/components/device/firmware-upgrade-panel/firmware-upgrade-panel.component.html
- packages/uhk-web/src/app/components/device/firmware-upgrade-panel/firmware-upgrade-panel.component.scss
- packages/uhk-web/src/app/components/device/firmware-upgrade-panel/firmware-upgrade-panel.component.ts
- packages/uhk-web/src/app/components/device/firmware-upgrade-panel/index.ts
- packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.scss
- packages/uhk-web/src/app/components/update-available/update-available.component.html
- packages/uhk-web/src/app/components/update-available/update-available.component.scss
- packages/uhk-web/src/app/pages/update-firmware.page.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
- packages/uhk-web/src/styles/_global.scss
- packages/uhk-web/src/styles/themes/_dark.scss
- packages/uhk-web/src/styles/themes/_light.scss
> feat: firmware update notification screens

- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.scss
> fix(web): macro editor cursor blinking

- packages/usb/debug-i2c.ts
> feat(usb): debug-i2c.ts script

- packages/uhk-web/src/app/components/macro/item/macro-item.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
> feat: hide new macro action item header

- packages/uhk-web/src/app/components/macro/action-editor/tab/mouse/macro-mouse.component.html
> fix: padding of macro actions

- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command.component.scss
> feat: change macro command title and tooltip

- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.scss
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts
- packages/uhk-web/src/app/services/app-init-factory.ts
- packages/uhk-web/src/app/services/monaco-editor-custom-theme.service.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/styles/_global.scss
- packages/uhk-web/src/styles/themes/_dark.scss
- packages/uhk-web/src/styles/themes/_light.scss
> feat: visualise the monaco-editor border like textarea border

- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
> fix: escape regexp characters of the scancode search expression

- packages/uhk-common/src/util/constants.ts
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
- packages/uhk-web/src/app/components/macro/header/macro-header.component.html
- packages/uhk-web/src/app/components/macro/header/macro-header.component.scss
- packages/uhk-web/src/app/components/macro/header/macro-header.component.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.ts
- packages/uhk-web/src/app/models/side-menu-page-state.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: don't allow to create more than 255 macro

- packages/uhk-web/src/app/components/macro/list/macro-list.component.scss
> fix: add extra padding to the macro list

- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
> feat: Select scancode field text when dropdown opens

- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
> feat: maximize scancode selector height

- packages/uhk-agent/src/services/device.service.ts
> fix: device recovery

- packages/uhk-common/src/config-serializer/assert.ts
- packages/uhk-common/src/config-serializer/config-items/secondary-role-action.ts
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.html
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/models/layer-option.ts
- packages/uhk-web/src/app/services/mapper.service.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/layer-options.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: missing fnX layer in Keypress/Secondary role

- packages/uhk-common/src/util/is-device-protocol-support-git-info.ts
> fix: semver import to work with es6 import

- packages/uhk-web/src/app/components/macro/action-editor/macro-action-editor.component.html
- packages/uhk-web/src/app/components/macro/action-editor/macro-action-editor.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command.component.ts
> fix: macro command saving on CTRL + ENTER

- README.md
> doc: set Node.js 16.16.0 in README.md

- packages/uhk-web/src/app/components/macro/action-editor/tab/delay/macro-delay.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/delay/macro-delay.component.ts
> feat: allow 65 seconds as max macro delay

- package.json
- packages/test-serializer/.gitignore
- packages/test-serializer/spec/test-convert-user-config-npm-script.spec.ts
- packages/test-serializer/tsconfig.json
closes UltimateHackingKeyboard/firmware#560
> fix: convert-user-config-to-bin npm script

- scripts/release.js
> fix: chmod 4755 the chrome-sandbox of linux build

- packages/uhk-usb/src/constants.ts
- packages/uhk-usb/src/uhk-operations.ts
- packages/usb/exec-macro-command.ts
(This was written mainly for testing... feel free to refactor as needed. Or request refactors of course.)
> Add exec-macro-command.ts

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/models/ipc-response.ts
- packages/uhk-web/src/app/models/update-firmware-success-payload.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/reducers/device.ts
technically when downgraded the firmware
> fix: don't save user config when firmware does not support it

- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.ts
- packages/uhk-web/src/app/util/has-none-ascii-characters.ts
- packages/uhk-web/src/app/util/index.ts
> fix: don't allow type non ascii charachters via ALT+numbers

- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
- packages/uhk-web/src/app/components/macro/action-editor/tab/key/macro-key.component.html
- packages/uhk-web/src/app/components/macro/action-editor/tab/key/macro-key.component.ts
- packages/uhk-web/src/app/components/macro/item/macro-item.component.scss
- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.scss
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
- packages/uhk-web/src/app/shared.module.ts
> fix: macro menu scancode dropdown panel visibility

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> fix: side menu state revalidation after device reconnected

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-common/src/models/ipc-response.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-web/src/app/components/device/advanced-settings/advanced-settings.page.component.html
- packages/uhk-web/src/app/components/device/advanced-settings/advanced-settings.page.component.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/advanced-settings.reducer.ts
- packages/uhk-web/src/app/store/reducers/app.reducer.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> feat: advanced-settings/change keyboard layout

- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/util/command-line.ts
- packages/uhk-agent/src/util/index.ts
- packages/uhk-agent/src/util/print-usb-devices.ts
- packages/uhk-common/src/models/command-line-args.ts
> feat: --print-usb-devices command line arguments

- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keystroke-key/svg-keystroke-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-one-line-text-key/svg-one-line-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-one-line-text-key/svg-one-line-text-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-secondary-role/svg-secondary-role.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-secondary-role/svg-secondary-role.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-single-icon-key/svg-single-icon-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-single-icon-key/svg-single-icon-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-text-icon-key/svg-text-icon-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-text-icon-key/svg-text-icon-key.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-two-line-text-key/svg-two-line-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-two-line-text-key/svg-two-line-text-key.component.ts
> fix: circle color of the secondary role symbol

- packages/uhk-common/src/models/application-settings.ts
- packages/uhk-web/src/app/components/agent/settings/settings.component.html
- packages/uhk-web/src/app/components/agent/settings/settings.component.ts
- packages/uhk-web/src/app/store/actions/app.ts
- packages/uhk-web/src/app/store/effects/app.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
> feat: support for non-tilted view of keyboard halves

- packages/uhk-web/src/app/components/layers/layers.component.html
- packages/uhk-web/src/app/components/layers/layers.component.scss
> fix: wrap color palette into multiple line

- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
- packages/uhk-web/src/app/services/capture.service.ts
- packages/uhk-web/src/app/services/mapper.service.ts
> feat: rename RAlt to RAlt(Gr) on Windows

- packages/uhk-common/src/util/copy-rgb-color.ts
- packages/uhk-common/src/util/index.ts
- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.ts
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
- packages/uhk-web/src/app/components/popover/tab/layer/layer-tab.component.ts
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.ts
- packages/uhk-web/src/app/components/popover/tab/mouse/mouse-tab.component.ts
- packages/uhk-web/src/app/components/popover/tab/none/none-tab.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.scss
- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
> fix: keep rgb color when remap KeyAction

- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts
- packages/uhk-web/src/styles.scss
> feat: use the JetBrains Mono font in Monaco editor

- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.html
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
- packages/uhk-web/src/app/components/layers/colors/color-palette-button.component.html
- packages/uhk-web/src/app/components/layers/colors/color-palette-button.component.ts
- packages/uhk-web/src/app/components/layers/layers.component.html
- packages/uhk-web/src/app/components/layers/layers.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/models/index.ts
- packages/uhk-web/src/app/models/modify-color-of-backlighting-color-palette-payload.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/actions/user-config.ts
- packages/uhk-web/src/app/store/effects/app.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: modify the color-palette by right click

- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/default-user-configuration.reducer.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
- packages/uhk-web/src/app/util/index.ts
- packages/uhk-web/src/app/util/set-svg-keyboard-cover-colors-of-all-layer.ts
- packages/uhk-web/src/app/util/set-svg-keyboard-cover-colors-of-layer.ts
> fix: keyboard cover colors of "add new keymap" and keymap tab of popover

- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.scss
> feat: dynamic padding around macro list on macro editing page

- packages/usb/send-command.ts
> feat: send-command.ts

- packages/uhk-web/package-lock.json
- packages/uhk-web/package.json
> chore: bump @fontsource/jetbrains-mono 5.0.5 => 5.0.12

- packages/uhk-agent/src/services/app.service.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-web/src/app/components/agent/settings/settings.component.html
- packages/uhk-web/src/app/components/agent/settings/settings.component.ts
- packages/uhk-web/src/app/services/app-renderer.service.ts
- packages/uhk-web/src/app/store/actions/app.ts
- packages/uhk-web/src/app/store/effects/app.ts
> feat: "Open configuration folder" link

- packages/uhk-web/src/app/components/macro/item/macro-item.component.html
- packages/uhk-web/src/app/components/macro/item/macro-item.component.scss
- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
> feat: optimize in-line editable command action for horizontal space

- packages/uhk-web/src/app/components/layers/layers.component.html
- packages/uhk-web/src/app/components/layers/layers.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
> fix: rename LayersComponent.select event to prevent conflict with html input.select

- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts
related story: #2087
https://stackoverflow.com/questions/58271107/offset-between-text-and-cursor-with-the-monaco-editor-angular-under-chrome-m
> fix: remeasure monaco editor fonts after custom font loaded

- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
> feat: make all firmware versions black

- .github/workflows/ci.yml
- scripts/release.js
The windows and mac installers are not signed for performance reason
> ci: create build artifacts

- packages/uhk-web/src/styles/_color-picker.scss
- packages/uhk-web/src/styles/_main.scss
> fix: color of color-picker.input element

- packages/uhk-common/src/config-serializer/config-items/macro-action/keymap.spec.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-key-cluster-left-module-config.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-touchpad-right-module-config.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-trackball-right-module-config.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-trackpoint-right-module-config.ts
- packages/uhk-web/src/app/services/user-config.json
> fix: change defaults of navigation modes

- packages/uhk-web/src/app/components/agent/about/about.component.html
- packages/uhk-web/src/app/components/agent/about/about.component.scss
- packages/uhk-web/src/app/components/agent/about/about.component.ts
- packages/uhk-web/src/app/components/agent/help-page/help-page.component.html
- packages/uhk-web/src/app/components/agent/help-page/help-page.component.scss
- packages/uhk-web/src/app/components/agent/help-page/help-page.component.ts
- packages/uhk-web/src/app/components/agent/settings/settings.component.html
- packages/uhk-web/src/app/components/agent/settings/settings.component.scss
- packages/uhk-web/src/app/components/agent/settings/settings.component.ts
- packages/uhk-web/src/app/components/device/led-settings/led-settings.component.scss
- packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.scss
- packages/uhk-web/src/app/components/keymap/header/keymap-header.component.html
- packages/uhk-web/src/app/components/macro/header/macro-header.component.html
- packages/uhk-web/src/app/components/uhk-header/uhk-header.html
> fix: consistent page margin

- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.html
> fix: Recover LED space tooltip blocks warning popup

- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
> fix: move the Modules menu directly under the Device menu

- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
> fix: swap Trackpoint and Touchpad menu items of Modules

- packages/uhk-web/src/app/components/add-on/add-on.component.html
> fix: increase touchpad hold continuation timeout slider maximum to 2000 ms

- packages/uhk-web/src/app/components/add-on/add-on.component.html
- packages/uhk-web/src/assets/images/acceleration-graph.svg
> Add acceleration diagram into tooltips again.

- packages/uhk-web/src/app/components/macro/item/macro-item.component.html
- packages/uhk-web/src/app/components/macro/item/macro-item.component.scss
- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
- packages/uhk-web/src/assets/images/vertical-grip-icon.svg
- packages/uhk-web/src/styles/uhk-icons/uhk-icon.scss
> fix: Drag and drop icon should be clearly separated from the rest of the row

- packages/uhk-web/src/app/components/device/typing-behaviour-page/typing-behaviour-page.html
> feat: add tooltip to the secondary roles header of the typing behaviour page

- packages/uhk-web/src/app/components/popover/popover.component.scss
> fix: popover gap

- package.json
- packages/uhk-common/src/config-serializer/config-items/macro-action/keymap.spec.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-key-cluster-left-module-config.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-touchpad-right-module-config.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-trackball-right-module-config.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/default-trackpoint-right-module-config.ts
- packages/uhk-common/src/config-serializer/config-items/module-configuration/module-property.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.spec.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
- packages/uhk-web/src/app/components/add-on/add-on.component.html
- packages/uhk-web/src/app/services/user-config.json
> feat: module config changes

- packages/uhk-web/src/app/components/add-on/add-on.component.html
- packages/uhk-web/src/app/components/add-on/add-on.component.ts
- packages/uhk-web/src/app/components/keymap/add/keymap-add.component.html
- packages/uhk-web/src/app/components/keymap/add/keymap-add.component.ts
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.html
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/models/navigate-to-module-settings-payload.ts
- packages/uhk-web/src/app/store/actions/user-config.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
> feat: "Back to keymap" from module pages

- packages/uhk-web/src/app/components/svg/keys/svg-icon-text-key/svg-icon-text-key.component.html
- packages/uhk-web/src/app/components/svg/keys/svg-text-icon-key/svg-text-icon-key.component.html
> fix: svg icon stroke width

- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.scss
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.ts
- packages/uhk-web/src/app/models/key-action-remap.ts
- packages/uhk-web/src/app/store/effects/macro.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: jump and add to macro button on macro selector of popover

- packages/uhk-web/src/app/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
> fix: border of keys when background color is very similar to key color

- packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.html
- packages/uhk-web/src/app/directives/ng-select-max-height.ts
- packages/uhk-web/src/app/shared.module.ts
> feat: increase select2 heights as max as possible

- packages/uhk-common/src/config-serializer/config-items/key-action/switch-keymap-action.ts
> fix: RGB color of SwitchKeymapAction when use binary serializer

- packages/uhk-web/src/app/components/svg/keys/svg-mouse-key/svg-mouse-key.html
- packages/uhk-web/src/app/components/svg/keys/svg-single-icon-key/svg-single-icon-key.component.html
closes:  #2247
also fixed mouse key icons
> fix: grey outline of icon keys

- packages/uhk-common/src/config-serializer/config-items/layer-name.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: "Remap on all layers" shouldn't remap modifier layers

- packages/uhk-web/src/app/components/add-on/add-on.component.html
- packages/uhk-web/src/app/components/add-on/add-on.component.ts
- packages/uhk-web/src/app/components/back-to/back-to.component.ts
- packages/uhk-web/src/app/shared.module.ts
> refactor: create back-to component

- packages/uhk-web/src/app/components/back-to/back-to.component.ts
- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.html
- packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.ts
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.scss
- packages/uhk-web/src/app/components/macro/header/macro-header.component.html
- packages/uhk-web/src/app/components/macro/header/macro-header.component.scss
- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.html
- packages/uhk-web/src/app/components/svg/wrap/svg-keyboard-wrap.component.ts
- packages/uhk-web/src/app/models/index.ts
- packages/uhk-web/src/app/models/open-popover.model.ts
- packages/uhk-web/src/app/models/selected-key.model.ts
- packages/uhk-web/src/app/store/actions/keymap.ts
- packages/uhk-web/src/app/store/effects/macro.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/layer-options.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> feat: "Back to keymap" from macro pages

- packages/usb/tsconfig.json
- tsconfig.json
For some reason the ts-config resolver path changed.
> chore: change ts-node config

- package-lock.json
- package.json
It will be used by the build system of the firmware
> chore: add tsx to dev dependencies

- packages/uhk-web/src/app/app.component.ts
- packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
- packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
- packages/uhk-web/src/app/components/macro/list/macro-list.component.html
- packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
- packages/uhk-web/src/app/models/selected-macro-action.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/device.ts
- packages/uhk-web/src/app/util/status-buffer-parser.ts
> feat: jump to macro errors on click

- packages/uhk-common/src/config-serializer/config-items/key-action/mouse-action.ts
- packages/uhk-web/src/app/components/popover/popover.component.html
- packages/uhk-web/src/app/components/popover/popover.component.ts
- packages/uhk-web/src/app/components/popover/tab/mouse/mouse-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/mouse/mouse-tab.component.scss
- packages/uhk-web/src/app/components/popover/tab/mouse/mouse-tab.component.ts
- packages/uhk-web/src/app/components/svg/keys/svg-mouse-click-key/svg-mouse-click-key.html
- packages/uhk-web/src/app/components/svg/keys/svg-mouse-click-key/svg-mouse-click-key.ts
- packages/uhk-web/src/app/components/svg/keys/svg-mouse-key/svg-mouse-key.ts
- packages/uhk-web/src/app/store/index.ts
closes #2167
Also removed the `extraMouseButtonsSupported` feature flag because Agent force to upgrade the firmware if it is not compatible.
> feat: expose 20 mouse buttons

- packages/uhk-web/src/app/components/device/led-settings/fade-timeout-slider.component.html
- packages/uhk-web/src/app/components/device/led-settings/fade-timeout-slider.component.ts
- packages/uhk-web/src/app/components/device/led-settings/led-settings.component.html
- packages/uhk-web/src/app/components/device/led-settings/led-settings.component.scss
- packages/uhk-web/src/app/components/device/led-settings/led-settings.component.ts
- packages/uhk-web/src/app/components/slider-wrapper/slider-wrapper.component.html
- packages/uhk-web/src/app/components/slider-wrapper/slider-wrapper.component.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/styles/_global.scss
> feat: LED fade timeout logarithmic slider

- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.html
> fix: put the "Create new macro for this key" tooltip on button

- packages/uhk-web/src/app/services/user-config.json
> fix: remove empty module config of layers in default user-config.json

- packages/kboot/src/kboot.ts
- packages/kboot/src/peripheral.ts
- packages/kboot/src/usb-peripheral.ts
- packages/kboot/test/test-peripheral.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/util/print-usb-devices.ts
- packages/uhk-agent/src/util/reenumerate-and-exit.ts
- packages/uhk-usb/src/uhk-hid-device.ts
- packages/uhk-usb/src/util.ts
- packages/uhk-usb/src/utils/get-current-uhk-device-product-by-bootloader-id.ts
- packages/uhk-usb/src/utils/get-current-uhk-device-product.ts
- packages/uhk-usb/src/utils/get-number-of-connected-devices.ts
- packages/uhk-usb/src/utils/get-uhk-devices.ts
- packages/uhk-usb/src/utils/validate-connected-devices.ts
- packages/usb/factory-update.ts
- packages/usb/get-module-bootloader-version.ts
- packages/usb/kboot-firmware-upgrade.ts
- packages/usb/reenumerate.ts
- packages/usb/update-device-firmware.ts
- packages/usb/update-firmwares-and-configs.ts
- packages/usb/update-firmwares.ts
- packages/usb/update-module-firmware.ts
> fix: use `devicesAsync` instead of `devices` of `node-hid`

- packages/kboot/package.json
- packages/uhk-usb/package-lock.json
- packages/uhk-usb/package.json
> chore: fix node-hid dependency of uhk-usb package

- packages/uhk-web/src/app/store/reducers/user-configuration.ts
> fix: set key color of uninitialised NoneAction

- packages/uhk-web/src/app/components/back-to/back-to.component.ts
- packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
> fix: Back to keymap link disappeared when saved or cancelled macro action item

- packages/uhk-web/src/app/components/editable-text/editable-text.component.html
- packages/uhk-web/src/app/components/editable-text/editable-text.component.ts
- packages/uhk-web/src/app/store/reducers/user-configuration.ts
Also fixes the immutability of the state
closes #2335
> fix: sanitize the description of the keymap

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/util/command-line.ts
- packages/uhk-common/src/models/command-line-args.ts
- packages/uhk-usb/src/utils/find-device-config-in-firmware-json.ts
- packages/uhk-usb/src/utils/get-device-user-config-path.ts
- packages/uhk-usb/src/utils/index.ts
Use checksum to identify installed firmware on UHK devices
> feat: ignore-firmware-checksums command line argument

- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-usb/src/utils/generate-device-serial-number.ts
- packages/uhk-usb/src/utils/index.ts
- packages/usb/factory-update-uhk80.ts
I tested with https://github.com/UltimateHackingKeyboard/firmware/commit/52c4dec3c884db232838fd315bb4d4355fba79a0 firmware and it does not set the serial number of the left half. Or just not return with updated value. The left half serial number always is `0000000000`
> chore: first write the hardware config and use same serial number of halves in factory-update-uhk80.ts

- .github/workflows/ci.yml
related  issue: https://github.com/electron/notarize/issues/219
> chore: downgrade macos runner to 13

- packages/uhk-usb/src/uhk-hid-device.ts
Make the firmware upgrade logging more compact
> chore: remove [UhkHidDevice] try to find MCU Bootloader log entry

- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
- packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.ts
- packages/uhk-web/src/app/services/svg-module-provider.service.ts
fixes the https://github.com/UltimateHackingKeyboard/agent/pull/2450#issuecomment-2567050469
I opened a new PR because the error not related to the referenced PR.
> fix: haves info detection when user set switch keymap action

- packages/uhk-usb/src/uhk-operations.ts
> fix: erase user configuration

- packages/uhk-web/src/app/components/device/host-connections/host-connections.component.html
> feat: switchover tooltip on the Connections page

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-usb/src/uhk-hid-device.ts
Decrease the chance of https://github.com/UltimateHackingKeyboard/agent/issues/2354
> refactor: remove unnecessary promises

- packages/uhk-common/src/models/hardware-modules.ts
- packages/uhk-common/src/util/constants.ts
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
- packages/uhk-web/src/app/store/reducers/device.ts
closes [#2501](https://github.com/UltimateHackingKeyboard/agent/issues/2501)
> feat: improve update firmware failed instructions

- README.md
Based on `package.json`, current version requires Node 20.x
> Update Node version in README

- packages/uhk-usb/src/uhk-operations.ts
closes [#2473](https://github.com/UltimateHackingKeyboard/agent/issues/2473)
> feat: keep reconnecting forever upon kboot firmware update

- packages/uhk-agent/src/services/smart-macro-doc.service.ts
- packages/uhk-web/src/app/services/smart-macro-doc-renderer.service.ts
- packages/uhk-web/src/app/store/actions/smart-macro-doc.action.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/smart-macro-doc.reducer.ts
> feat: fallback to bundled smart macro documentation

- packages/uhk-web/src/app/components/popover/tab/device/device-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/device/device-tab.component.ts
> feat: comment out the "sleep mode" device action

- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/util/delete-user-config-history.ts
- packages/uhk-agent/src/util/index.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.html
- packages/uhk-web/src/app/components/device/configuration/device-configuration.component.ts
- packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.html
- packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.ts
- packages/uhk-web/src/app/models/user-config-history-component-state.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/store/actions/user-configuration-history.actions.ts
- packages/uhk-web/src/app/store/effects/user-configuration-history.effects.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/user-configuration-history.reducer.ts
> feat: delete device configuration history

- packages/uhk-web/src/app/store/effects/keymap.ts
story: https://github.com/UltimateHackingKeyboard/agent/issues/2491#issuecomment-2584510545
> fix: selected keymap in the side menu after deleting or duplicating a keymap

- packages/uhk-common/src/config-serializer/config-items/scancodes.ts
- packages/uhk-web/src/app/services/mapper.service.ts
> feat: alias for iso #

- packages/uhk-web/src/app/services/app-renderer.service.ts
the bug introduced with #2604 PR
> fix: show firmware upgrade log entries

- packages/uhk-web/src/app/components/keymap/edit/keymap-edit-guard.service.ts
> fix: default keymap not selected in the side menu on startup

- packages/kboot/readme.md
- packages/kboot/src/kboot.ts
- packages/kboot/src/peripheral.ts
- packages/kboot/src/usb-peripheral.ts
- packages/kboot/test/zzz-uhk-integration-tests.spec.ts
- packages/uhk-agent/src/electron-main.ts
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-usb/src/uhk-hid-device.ts
- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-usb/src/util.ts
- packages/usb/factory-update-uhk80.ts
- packages/usb/get-module-bootloader-version.ts
> refactor: use node-hid async operations

- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
- packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
> fix: extend the firmware upgrade error checklist

- package.json
- packages/uhk-common/src/config-serializer/config-items/battery-charging-mode.ts
- packages/uhk-common/src/config-serializer/config-items/index.ts
- packages/uhk-common/src/config-serializer/config-items/serialisation-info.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.spec.ts
- packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
- packages/uhk-web/src/app/components/device/battery-settings/battery-settings.component.html
- packages/uhk-web/src/app/components/device/battery-settings/battery-settings.component.scss
- packages/uhk-web/src/app/components/device/battery-settings/battery-settings.component.ts
- packages/uhk-web/src/app/components/device/device.routes.ts
- packages/uhk-web/src/app/components/device/index.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/components/side-menu/side-menu.component.ts
- packages/uhk-web/src/app/components/slider-wrapper/slider-wrapper.component.html
- packages/uhk-web/src/app/components/slider-wrapper/slider-wrapper.component.ts
- packages/uhk-web/src/app/services/user-config-80.json
- packages/uhk-web/src/app/shared.module.ts
closes: #2619 
required firmware https://github.com/UltimateHackingKeyboard/firmware/pull/1218
> feat: battery settings

- packages/uhk-agent/package-lock.json
- packages/uhk-agent/package.json
- packages/uhk-agent/src/services/device.service.ts
- packages/uhk-agent/src/services/logger.service.ts
- packages/uhk-agent/src/services/zephyr-log.service.ts
- packages/uhk-common/src/models/device-connection-state.ts
- packages/uhk-common/src/models/index.ts
- packages/uhk-common/src/models/zephyr-log-entry.ts
- packages/uhk-common/src/util/ipcEvents.ts
- packages/uhk-usb/src/constants.ts
- packages/uhk-usb/src/models/device-state.ts
- packages/uhk-usb/src/uhk-hid-device.ts
- packages/uhk-usb/src/uhk-operations.ts
- packages/uhk-web/src/app/components/device/advanced-settings/advanced-settings.page.component.html
- packages/uhk-web/src/app/components/device/advanced-settings/advanced-settings.page.component.ts
- packages/uhk-web/src/app/services/device-renderer.service.ts
- packages/uhk-web/src/app/store/actions/advance-settings.action.ts
- packages/uhk-web/src/app/store/effects/advanced-settings.effects.ts
- packages/uhk-web/src/app/store/index.ts
- packages/uhk-web/src/app/store/reducers/advanced-settings.reducer.ts
- packages/uhk-web/src/app/store/reducers/device.ts
- packages/usb/get-device-state.ts
> feat: expose zephyr logs

- packages/uhk-web/src/app/components/popover/tab/device/device-tab.component.html
- packages/uhk-web/src/app/components/popover/tab/device/device-tab.component.ts
> feat: reactivate sleep mode device action

- packages/uhk-web/src/app/components/xterm/xterm.component.html
- packages/uhk-web/src/app/pipes/escape-html.pipe.ts
- packages/uhk-web/src/app/pipes/index.ts
- packages/uhk-web/src/app/shared.module.ts
- packages/uhk-web/src/app/store/reducers/advanced-settings.reducer.ts
[#2650](https://github.com/UltimateHackingKeyboard/agent/issues/2650)
> fix: copy the pure zephyr log to the clipboard

- packages/uhk-web/src/app/components/back-to/back-to.component.ts
- packages/uhk-web/src/app/components/keymap/add/keymap-add.component.ts
- packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
- packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.ts
- packages/uhk-web/src/app/store/effects/macro.ts
> fix: encode keymap abbreviation in backUrl

- packages/uhk-web/src/app/components/back-to/back-to.component.ts
- packages/uhk-web/src/app/components/side-menu/side-menu.component.html
- packages/uhk-web/src/app/models/side-menu-page-state.ts
- packages/uhk-web/src/app/store/index.ts
> fix: handle / as keymap abbreviation

- packages/uhk-web/src/app/models/undo-user-config-data.ts
- packages/uhk-web/src/app/services/datastorage-repository.service.ts
- packages/uhk-web/src/app/services/default-user-configuration.service.ts
- packages/uhk-web/src/app/store/actions/device.ts
- packages/uhk-web/src/app/store/effects/device.ts
- packages/uhk-web/src/app/store/effects/user-config.ts
- packages/uhk-web/src/app/store/reducers/advanced-settings.reducer.ts
- packages/uhk-web/src/app/store/reducers/device.ts
- packages/uhk-web/src/renderer/services/electron-datastorage-repository.service.ts
closes [#2429](https://github.com/UltimateHackingKeyboard/agent/issues/2429)
> feat: manage connected device with query parameters in web version
