config-serializer/assert.ts
config-serializer/config-items/DelayMacroAction.ts
config-serializer/config-items/DualRoleKeystrokeAction.ts
config-serializer/config-items/HoldKeyMacroAction.ts
config-serializer/config-items/HoldModifiersMacroAction.ts
config-serializer/config-items/HoldMouseButtonsMacroAction.ts
config-serializer/config-items/KeyMap.ts
config-serializer/config-items/KeystrokeAction.ts
config-serializer/config-items/KeystrokeModifiersAction.ts
config-serializer/config-items/KeystrokeWithModifiersAction.ts
config-serializer/config-items/Macro.ts
config-serializer/config-items/Module.ts
config-serializer/config-items/ModuleConfiguration.ts
config-serializer/config-items/MouseAction.ts
config-serializer/config-items/MoveMouseMacroAction.ts
config-serializer/config-items/PlayMacroAction.ts
config-serializer/config-items/PressKeyMacroAction.ts
config-serializer/config-items/PressModifiersMacroAction.ts
config-serializer/config-items/PressMouseButtonsMacroAction.ts
config-serializer/config-items/ReleaseKeyMacroAction.ts
config-serializer/config-items/ReleaseModifiersMacroAction.ts
config-serializer/config-items/ReleaseMouseButtonsMacroAction.ts
config-serializer/config-items/ScrollMouseMacroAction.ts
config-serializer/config-items/SwitchKeymapAction.ts
config-serializer/config-items/SwitchLayerAction.ts
config-serializer/config-items/UhkConfiguration.ts

to make them non-static-like. Based on http://stackoverflow.com/questions/35493375/typescript-class-with-property-decorator-acts-as-if-static
Let me know if there is a better way to import the assertions
fix for #36

changing how assertions access instance variables 

---

src/components/macro/header/macro-header.component.ts
src/components/macro/item/macro-item.component.html
src/components/macro/item/macro-item.component.scss
src/components/macro/item/macro-item.component.ts
src/components/macro/macro.component.html
src/components/macro/macro.component.scss
src/components/macro/macro.component.ts
src/components/popover/tab/macro/macro-tab.component.html
src/store/actions/macro.ts
src/store/effects/macro.ts
src/store/reducers/macro.ts

Because of the problems with data layer logic I needed to do some refactoring (because I was already refactoring I also added some UX improvements) :

Data layer - Macro & UX improvments

---

src/config-serializer/config-items/Module.ts
src/config-serializer/config-items/key-action/helper.ts

PR resolving #157.
Problem is that we are using array and not objects. And for example if you set action for key that is in the middle of the module you would have empty elements in the array before.
For example:
You set action for backspace key. This is the last element in layer one in module one. That means that you would create array with `keyActions[7]= keyAction`. When we are reading and saving this into JSON and array, you have 6 empty elements before. As you can see on the image in #157 JSON contains null for all empry elements before.
What I did is a **temporary solution**. Proper solution would be to remove array and use objects. This way you wouldn't have any problems with this. But this would require quite a lot of work.
**svg-keyboar-wrap.component.ts**
```js …
```

Fixed null problem

---

src/components/svg/module/svg-module.component.html
src/components/svg/wrap/svg-keyboard-wrap.component.html
src/components/svg/wrap/svg-keyboard-wrap.component.scss
src/components/svg/wrap/svg-keyboard-wrap.component.ts

PR based on #102 
@mondalaci Please check it out

Tooltip UX fixes

---

.editorconfig
tsconfig.json
tslint.json

We aggreed to use 2 indent size in json files. The reason is npm use 2 indent in package.json and this is the defacto

style(editorconfig): Add json rule to editor config

---

electron/src/services/electron-datastorage-repository.service.ts

The feature will implement later.
Close, #325

fix(device): Agent-electron should always read the configuration from UHK

---

.stylelintrc.json
package.json

Deprecation Warning: 'selector-no-id' has been deprecated and in 8.0 will be removed.
Instead use 'selector-max-id' with '0' as its primary option.
See: https://stylelint.io/user-guide/rules/selector-no-id/

style: Fix styelint 'selector-no-id' warning

---

shared/src/store/reducers/user-configuration.ts

in #360 mentioned the generateAbbr method not contains 0 and 1 and it is a bug or not.
I think it is not bug because a function is calculate the next abbreviation and if we allow the 0 and 1 the the next calculated value will be xx0. So I added the 0, but I think I have to delete the 1 from the string and the new abbreviation will xx2 instead if xx0.
@mondalaci What is your opinion?

fix(keymap): allow 0 in keymap abbr when rename

---

shared/src/components/svg/keys/svg-keyboard-key/svg-keyboard-key.component.ts
shared/src/components/svg/module/svg-module.component.html

This fixes #367 by adding tabindex attribute to key svg element so Firefox can properly focus the key. Otherwise focus, focusout events do not get fired and using mouse middle click to change key quickly does not work in Firefox. 
Only Firefox v52+ support focusout event so this will still not work correctly on older FF versions than that.
Also fixes small typo in onKeyUp (was "onKeyUpe").

Fix key capture on Firefox

---

packages/uhk-agent/src/services/device.service.ts
packages/uhk-usb/src/constants.ts

Rename SystemPropertyIds.UserConfigSize => SystemPropertyIds.MaxUserConfigSize because it better describe which date will return from device

refactor(device): Rename UserConfigSize => MaxUserConfigSize

---

packages/uhk-web/src/app/components/missing-device/missing-device.component.html
packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.html
packages/uhk-web/src/app/components/uhk-message/uhk-message.component.html
packages/uhk-web/src/app/components/uhk-message/uhk-message.component.ts
packages/uhk-web/src/app/pages/loading-page/loading-device.page.ts

Renaming eliminate the default behaviour of the title attribute of the
HTML elements.
close: #454

fix(app): Rename the title property of the uhk-message component

---

.travis.yml

g++-multilib library need to build ia32 and ARM specific target in x64 architecture

ci: Add g++-multilib to travis

---

packages/uhk-web/src/app/services/user-config.json

Partially resolves https://github.com/UltimateHackingKeyboard/agent/issues/535
Flips mouse scroll up/down on 
- Colemak for Mac 
- Dvorak for Mac 
- QWERTY for Mac 
Logic to change this in the configurator is still needed.

Invert scroll on mac

---

packages/uhk-agent/src/electron-main.ts

Maybe solve the auto-update failed on linux
related: #597

fix: use app.exit() instead of "quit" when "window-all-closed" electron event occurred

---

packages/uhk-agent/src/services/app-update.service.ts

related to #639 
Not show any notification about the update process if the update started automatically at startup, but show if user manually clicked on the check for update link.

feat: only send auto update notification when user indicated the update

---

packages/uhk-usb/src/uhk-hid-device.ts

Not show the permission screen on mac and windows if device is not plugged

fix: permission detection on win and mac

---

packages/uhk-usb/src/util.ts

The snooze call is skipped in the try block when the command throws an
exception.  As a result, the command tries maxTry times as fast as
possible.
The fix is to move the snooze call outside of the try block.
PS: #GotMyUHK

Fix left half timeout during fw update (#567)

---

packages/uhk-usb/src/uhk-hid-device.ts

The close operation clear the device cache and force to create new USB device for the next operation

fix: close device when any error occurred in the communication

---

packages/uhk-web/src/app/services/user-config.json

Not sure if this is only my system but the Sleep key on the Fn layer does not work on my Macbook. Changed it to be the shortcut on the official list of shortcut published by Apple: https://support.apple.com/en-us/HT201236 and it works as expected.

Fix Sleep key for macOS users in Mac keymaps and Fn layers

---

package-lock.json
package.json

I reviewed the electron changelog and it does not contain any breaking changes that have an effect to the Agent.
node-hid also compatible with this electron.
I tested the following options without any error:
- save user configuration
- upgrade firmware

chore: upgrade electron => 2.0.16

---

packages/kboot/src/usb-peripheral.ts
packages/kboot/test/test-peripheral.ts
packages/uhk-agent/src/util/save-extract-firmware.ts
packages/uhk-common/src/config-serializer/uhk-buffer.ts
packages/uhk-usb/src/uhk-hid-device.ts
packages/uhk-usb/src/uhk-operations.ts
packages/uhk-usb/src/util.ts
packages/uhk-web/src/app/store/effects/user-config.ts
packages/usb/blink-led-pwm-brightness.js
packages/usb/blink-test-leds.js
packages/usb/erase-user-config.js
packages/usb/get-adc-value.js
packages/usb/get-config-size.js
packages/usb/get-debug-info.js
packages/usb/get-device-state.js
packages/usb/get-i2c-health.js
packages/usb/get-left-firmware-version.js
packages/usb/get-right-firmware-version.js
packages/usb/get-slave-i2c-errors.js
packages/usb/get-uptime.js
packages/usb/hidapi-sync-stress-test.js
packages/usb/read-config.js
packages/usb/set-led-pwm-brightness.js
packages/usb/uhk.js

The `new Buffer()` is deprecated and vulnerable.
The upgrade is prerequisite of the Electron 3.x upgrade

refactor: use Buffer.from and Buffer.alloc instead of new Buffer()

---

packages/uhk-web/package-lock.json
packages/uhk-web/package.json

The new version uses newer version of the `handlebars` and it
protected from `Prototype Pollution` vulnerability.

chore: upgrade karma-coverage-istanbul-reporter => 2.0.6

---

package.json
scripts/generate-svg-sprites.js

The fs-extra has the same `ensureDirSync` function that functionality is the same than `mkdirp`. It decreases the direct dependencies of the Agent

chore: use fs-extra instead of mkdirp package

---

packages/uhk-usb/src/util.ts
packages/usb/kboot-firmware-upgrade.ts

With this script, we can test the new kboot firmware upgrade without new release
run the following command in the agent root directory:
`$ node -r ts-node/register -r source-map-support/register packages/usb/kboot-firmware-upgrade.ts`

chore(usb): add kboot-firmware-upgrade script

---

packages/uhk-web/src/main-renderer.ts

The `npm run server:electron` build result much more simmilar to the production build

chore: use preserveWhitespaces = true in electron renderer build

---

packages/uhk-usb/src/util.ts

The modification helps to handle correctly the ES6 default exports.
The firmware upgrade run correctly in the electron version and kboot-firmware-upgrade.ts script

fix: es6 module loading

---

packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html

The `.tar.bz2` value does not allow selecting the firmware file on Mac

fix: allowed file extension for the firmware file upload

---

package.json
packages/uhk-agent/package.json
packages/uhk-agent/src/electron-main.ts
packages/uhk-agent/src/services/device.service.ts
packages/uhk-common/src/models/command-line-args.ts

feat: Use native kboot firmware update on Linux and Mac. Use blhost on Windows.

---

packages/uhk-common/src/config-serializer/README.md

Fix for #1083: 
`directorx` -> `directory`

Fixed typo (#1083)

---

package-lock.json
package.json

It is a major version change and changing the log output format.
File log entry example
[2019-11-01 21:43:49.550] [debug] [UhkHidDevice] USB[W]: 09 
Console log entry format
21:49:15.115 › [UhkHidDevice] USB[W]: 09

chore: upgrade electron-log => 3.0.8

---

packages/uhk-agent/src/services/app-update.service.ts
packages/uhk-common/src/models/application-settings.ts
packages/uhk-common/src/models/auto-update-settings.ts
packages/uhk-common/src/models/index.ts
packages/uhk-web/src/app/components/agent/settings/settings.component.html
packages/uhk-web/src/app/components/agent/settings/settings.component.ts
packages/uhk-web/src/app/components/auto-update-settings/auto-update-settings.html
packages/uhk-web/src/app/components/auto-update-settings/auto-update-settings.ts
packages/uhk-web/src/app/services/datastorage-repository.service.ts
packages/uhk-web/src/app/store/actions/app.ts
packages/uhk-web/src/app/store/actions/auto-update-settings.ts
packages/uhk-web/src/app/store/effects/app.ts
packages/uhk-web/src/app/store/effects/auto-update-settings.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/app-update.reducer.ts
packages/uhk-web/src/app/store/reducers/auto-update-settings.ts
packages/uhk-web/src/renderer/services/electron-datastorage-repository.service.ts

Summary
- renamed AutoUpdateSettings => ApplicationSettings
- deleted the AutoUpdateSettings reading/saving Actions and effects
- added the ApplicationSettings reading/saving Actions and effects
- fix typo
- remove unused imports
- simplified the input properties of AutoUpdateSettings component

refactor: rename AutoUpdateSettings => ApplicationSettings

---

appveyor.yml

Chrome 78 installed in the Visual Studio 2017 image

ci: remove chromium installation on appveyor

---

packages/uhk-web/package.json
packages/uhk-web/src/app/services/app-renderer.service.ts

With electron-logger 3.x (PR #1089) the logging syntax changed. We did not recognize these changes that change at the package upgrade.

fix: firmware upgrade status messages

---

packages/uhk-agent/src/electron-main.ts
packages/uhk-agent/src/services/device.service.ts
packages/uhk-agent/src/services/sudo.service.ts
packages/uhk-web/src/app/models/index.ts
packages/uhk-web/src/app/models/navigation-payload.ts
packages/uhk-web/src/app/store/actions/app.ts
packages/uhk-web/src/app/store/effects/app.ts
packages/uhk-web/src/app/store/effects/user-config.ts

fix #1128 
The root cause was the UHK Poller ran under the permission setup and broke the user config reading
Tests:
**1.) Update udev file 10/10 success**
- modify udev file
- reload udev setting
- reconnect keyboard
- start agent
- Use Update udev file button
- Agent start success full
**2.) Sep up permissions 10/10 success**
- delete udev file
- reload udev setting
- reconnect keyboard
- start agent
- Use Setup Permission button
- Agent start success full
**3.) Update udev file with unconnected keyboard 5/5 success**
- unplug agent
- modify udev file
- reload udev setting
- start agent
- Use Update udev file button
- UHK Unpluged screen visible
- plug keyboard 
- Agent start success full
**4.) Set Permission with unconnected keyboard 5/5 success**
- unplug agent
- delete udev file
- …

fix: navigation after udev update

---

packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
packages/uhk-web/src/app/components/device/firmware/device-firmware.component.scss

fixes the following problem
I think the angular 9 upgrade caused the problem

fix: positions of the firmware upgrade buttons

---

packages/uhk-common/package.json

The secondaryRole.json deleted in the #1211 PR

chore: delete the copy:secondary-roles npm script

---

package-lock.json
package.json
packages/uhk-agent/src/custom_types/command-line-args.d.ts
packages/uhk-agent/src/custom_types/command-line-usage.d.ts
packages/uhk-agent/src/custom_types/decompress.d.ts
packages/uhk-agent/src/services/app-update.service.ts
packages/uhk-agent/src/util/command-line.ts
packages/uhk-agent/src/util/save-extract-firmware.ts
packages/uhk-agent/src/util/window.ts
packages/uhk-common/src/util/create-md5-hash.ts
packages/uhk-common/src/util/user-configuration-history-helpers.ts
tsconfig.json

The new es6 module packages are not compatible with the old TypeScript config setup, so uses the `esModuleInterop: true`.
Summary of the modifications:
- Uses official typings of the following packages
- command-line-args
- command-line-usage
- decompress
- Change the module import syntax of the modules that support default exports.
Following functions tested:
- Setup udev permission on Linux
- Modify user configuration and save to keyboard
- Restore default configuration
- Export user config
- Import user config
- Restore user config from the history
- Save/load application settings

chore: use esModuleInterop: true

---

package-lock.json
package.json
packages/uhk-agent/src/services/logger.service.ts
packages/uhk-web/src/renderer/services/electron-log.service.ts

Change the log file name from `log.log` => `uhk-agent.log`.
The log folder does not change.

chore: upgrade electron-log => 4.2.0

---

packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.ts

The new Chrome 87.0.4280.88 changed the text length calculation. This version will be used in the newer version of electrons so I though I implement the fix now.
The fix: add an extra pixel to the calculated length.
Before the fix
After:

fix(web): auto-grow-input non edit mode width calculation

---

packages/uhk-usb/src/util.ts

The new node-hid v2.1.1 returns with the interface value.

refactor: remove usage and usagePage from 0 interface detection

---

packages/uhk-agent/src/electron-main.ts
packages/uhk-agent/src/services/device.service.ts
packages/uhk-agent/src/util/save-extract-firmware.ts
packages/uhk-common/src/models/device-connection-state.ts
packages/uhk-common/src/models/hardware-modules.ts
packages/uhk-common/src/models/index.ts
packages/uhk-common/src/models/module-slot-id.ts
packages/uhk-common/src/models/module-slot-to-i2c-adress.ts
packages/uhk-common/src/models/uhk-products.ts
packages/uhk-common/src/util/find-uhk-module-by-id.ts
packages/uhk-common/src/util/find-uhk-module-by-slot-name.ts
packages/uhk-common/src/util/index.ts
packages/uhk-common/src/util/map-i2c-address-to-module-name.ts
packages/uhk-common/src/util/map-i2c-address-to-slot-id.ts
packages/uhk-common/src/util/to-hex-string.ts
packages/uhk-usb/src/constants.ts
packages/uhk-usb/src/models/tmp-firmware.ts
packages/uhk-usb/src/uhk-hid-device.ts
packages/uhk-usb/src/uhk-operations.ts
packages/uhk-usb/src/utils/get-module-firmware-path.ts
packages/uhk-usb/src/utils/index.ts
packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/device.ts
packages/usb/get-left-firmware-version.ts
packages/usb/update-module-firmware.ts

closes: #1428
BREAKING CHANGES:
- the `<moduleSlot>` argument replaced with `<i2cAddress>` of the `update-module-firmware.ts` USB script changed. Hexadecimal and decimal format supported.

feat: update module firmwares

---

packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
packages/uhk-web/src/app/models/undo-user-config-data.ts
packages/uhk-web/src/app/store/effects/macro.ts
packages/uhk-web/src/app/store/effects/user-config.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/user-configuration.ts

close: #1454
Logic
- when a macro deleted it is not last macro than navigate to the below macro
- when a macro deleted it is last macro than navigate to the above macro
- when the macro deleted and after the user undo the deletion than navigate to the restored macro

feat: when a macro is deleted, navigate to the below macro

---

packages/uhk-agent/src/services/device.service.ts

This PR fixes 2 bug:
- Agent tries to read the module info when the device has been unplugged.
- throw exception when can't read the hardware info. The `getHardwareModules` returned with the exception instead of throw it. It can cause null pointer exception.

fix: hardware module info reading from keyboard

---

packages/uhk-agent/src/electron-main.ts
packages/uhk-agent/src/services/app.service.ts
packages/uhk-agent/src/services/device.service.ts
packages/uhk-common/src/models/app-start-info.ts
packages/uhk-web/src/app/app.routes.ts
packages/uhk-web/src/app/store/effects/app.ts

story: #1492
The application start event and the device service initialisation had race condition if the device connection state query is slow - mainly on windows.

fix: connection state query at application start

---

packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html

fix: equal bottom and top margin of the firmware upgrade error panel

---

packages/uhk-agent/src/services/device.service.ts
packages/uhk-agent/src/util/reenumerate-and-exit.ts
packages/uhk-common/src/models/uhk-products.ts
packages/uhk-usb/src/uhk-hid-device.ts
packages/uhk-usb/src/utils/get-uhk-devices.ts
packages/uhk-usb/src/utils/index.ts
packages/uhk-usb/src/utils/usb-device-json-formatter.ts

closes: #1500 
Summary:
- show only UHK USB devices in the logs and the firmware upgrade screen
- log only "Added" and "Removed" UHK USB devices
- show the "vendorId" and "productId" in hex format
- not repeat the "Could not find reenumerated device: <Device>. Waiting..." and "Available devices unchanged" log messages. Instead of it add a `.` after "Waiting..."
- before
- after

feat: simplify USB device list

---

packages/uhk-agent/src/services/device.service.ts

story: #1521
It prevents race condition

fix: stop USB polling before read hardware modules at firmware upgrade

---

packages/uhk-agent/src/services/device.service.ts
packages/uhk-common/src/util/get-slot-id-name.ts
packages/uhk-common/src/util/index.ts
packages/uhk-usb/src/uhk-operations.ts

Summary:
- log the OS version and architecture
- add the `[DeviceService] ` prefix to the firmware upgrade logs
- log the module slot name instead of the id

chore: reorganise firmware upgrade logging

---

packages/uhk-web/src/app/app.component.html
packages/uhk-web/src/app/app.component.scss
packages/uhk-web/src/app/components/device/configuration/device-configuration.component.scss
packages/uhk-web/src/app/components/device/configuration/device-configuration.component.ts
packages/uhk-web/src/app/components/device/firmware/device-firmware.component.scss
packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts
packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.scss
packages/uhk-web/src/app/components/device/recovery-mode/recovery-mode.component.ts
packages/uhk-web/src/app/components/missing-device/missing-device.component.ts
packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.html
packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.scss
packages/uhk-web/src/app/components/privilege-checker/privilege-checker.component.ts
packages/uhk-web/src/app/components/side-menu/side-menu.component.scss
packages/uhk-web/src/app/pages/loading-page/loading-device.page.ts
packages/uhk-web/src/app/pages/main-page/main.page.html
packages/uhk-web/src/app/pages/main-page/main.page.ts
packages/uhk-web/src/app/pages/multi-device.page.ts
packages/uhk-web/src/styles/_global.scss
packages/uhk-web/src/styles/_mixins.scss
packages/uhk-web/src/styles/_variables.scss

closes: #1603
The easiest way to test the firmware upgrade while the update panel is visible : modify the [line](https://github.com/UltimateHackingKeyboard/agent/blob/3990877496dc273f7a066ad61c0b27398e8bfc0a/packages/uhk-web/src/app/store/reducers/app-update.reducer.ts#L51)
```typescript
export const getShowAppUpdateAvailable = (state: State) => true;
```

fix: refactor generic layout

---

packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.html
packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.ts
packages/uhk-web/src/app/models/user-config-history-component-state.ts
packages/uhk-web/src/app/store/index.ts

feat: show "Same as current" for every current row after the first "Current" row in the user configuration history.

---

packages/uhk-web/src/app/components/auto-grow-input/auto-grow-input.component.ts
packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
packages/uhk-web/src/app/components/macro/macro.routes.ts
packages/uhk-web/src/app/store/effects/macro.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/user-configuration.ts

Summary:
- create `macroNavigated$` effect to detect the selected macro ID
- replace `selectedMacroIdAfterRemove` with `selectedMacroId` in user-configuration state
- fix content selection of the AutoGrowInputComponent

refactor: selected macro logic

---

packages/uhk-web/src/app/app.component.scss

fix: z-index of the save to keyboard button

---

packages/uhk-web/src/app/services/smart-macro-doc-service.ts
packages/uhk-web/src/app/store/effects/smart-macro-doc.effect.ts
smart-macro-docs/script.mjs

Summary
- introduced the `agent-message-context` event. The event will dispatch if any of the message property changes. Currently, the `modules` relevant
- removed the `modules` property from the `gent-message-editor-got-focus` and `agent-message-editor-lost-focus` actions
- introduced the `doc-message-open-link` action. Parameters of the message:
- 'url': Agent will open the URL in a browser window

feat: open smart macro doc links in browser

---

packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.ts

fix: scancode field not updated from Capture keystroke if dropdown was opened

---

packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts
packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.ts
packages/uhk-web/src/app/util/constants.ts
packages/uhk-web/src/app/util/index.ts

Summary:
- move the `NON_ASCII_REGEXP` into a util file because, used in multiple places
- use the browser keydown event.key instead of the monaco editor code event, because the browser keydown event.key contains the ascii key code

fix: detect non ASCII character keydown in macro-command-editor

---

packages/uhk-web/src/app/store/effects/smart-macro-doc.effect.ts
packages/uhk-web/src/app/store/index.ts
smart-macro-docs/index.html
smart-macro-docs/script.mjs

related firmware PR: UltimateHackingKeyboard/firmware#516
Summary:
- send the firmware git repo of right half in `agent-message-context` message
- in browser mode uses the master branch of UHK official firmware. It is not testable because we use a dummy smart macro doc in the web version

feat: send the firmware git repo info in `agent-message-context` message

---

package-lock.json
package.json
scripts/release.js

It is the same package, just developers publish it under @electron org

chore: switch from electron-notarize to @electron/notarize

---

packages/uhk-web/src/app/services/smart-macro-doc-service.ts

Covered case:
- click into the smart macro command input that has value
- select the whole content with CTRL + A
- press backspace. It deletes the content of the editor but the smart macro sidebar hadn't been updated.

fix: always update smart macro doc when macro command changing

---

package-lock.json
package.json

Later versions of lerna support native npm workspaces, see https://lerna.js.org/docs/getting-started#package-dependency-management.

chore: upgrade lerna 5.6.2 -> 6.5.1

---

packages/uhk-usb/src/util.ts
packages/uhk-usb/src/utils/is-os-provide-usb-interface.ts

fix: macOS 13.3 does not fill interface property of USB Device

---

packages/uhk-web/src/app/components/macro/item/macro-item.component.html
packages/uhk-web/src/app/components/macro/item/macro-item.component.scss
packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
packages/uhk-web/src/app/components/svg/svg-sprite-image.ts
packages/uhk-web/src/app/shared.module.ts

closes: #2018
Normal line
Hovered line

fix: show scancode icons in macro item header

---

packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts

closes #2017
The new behaviour is 
- when creating a new macro command action then it is saved with LF
- when loading a user configuration that contains macro with CRLF then it will not change until the user modifies the macro. After the macro action has been edited the EOL character will change to LF
- when user copy paste a text that contains CRLF EOL then EOL will be converted to LF
Tested on Mac and Windows

fix: macro-command-editor always use LF end of line character

---

packages/uhk-web/package-lock.json
packages/uhk-web/package.json
packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.scss
packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command-editor.component.ts

If user edited the last line then the suggestion widget was not visible.

fix: suggestion widget visibility, bump monaco-editor 0.41.0 => 0.44.0

---

packages/uhk-web/src/app/components/device/firmware/device-firmware.component.html
packages/uhk-web/src/app/components/popover/tab/keymap/keymap-tab.component.html
packages/uhk-web/src/styles/themes/_dark.scss

closes: #2149
Summary:
- tried to follow the bootstrap 5 dark style. Because in the future we would like to switch to BS dark mode instead of custom dark mode.
- use `text-body-secondary` as successor `text-muted`
- `--bs-secondary-color` use the `$secondary` color in dark mode
Also fixing the keymap selector of the `popover` when the list item keymap equal to the currently selected keymap.
Before:
After:

fix: color of text-muted css selector

---

packages/uhk-web/src/app/components/circle-tooltip/circle-tooltip.component.ts

The CircleTooltip component currently used only on the new Typings behaviour and Module config pages.
In the future, we will use it everywhere.
closes: #2205

fix: align CircleTooltip to top if there not enough space at bottom

---

packages/uhk-web/src/app/components/device/led-settings/led-settings.component.html
packages/uhk-web/src/app/components/macro/edit/macro-edit.component.scss
packages/uhk-web/src/styles/_global.scss
packages/uhk-web/src/styles/_table.scss

Had to refactor h1 header to use padding instead of margin to remove extra scrollbars of macro page.
closes #2172

fix: don't hide the smart macro editor autocomplete popup

---

packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts
packages/uhk-web/src/app/components/popover/popover.component.html
packages/uhk-web/src/app/components/popover/tab/macro/macro-tab.component.ts
packages/uhk-web/src/app/components/side-menu/side-menu.component.html
packages/uhk-web/src/app/models/side-menu-page-state.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/user-configuration.ts

This PR fixes 
- the popover position when navigating between keymaps or from keymap to other page and back and opens the popover. 
- the remap on all keymaps and layers checkboxs state are preserved when navigation to macro page and back to keymap

fix: keymap navigation

---

packages/uhk-web/src/app/app.component.ts
packages/uhk-web/src/app/components/agent/settings/settings.component.html
packages/uhk-web/src/app/components/circle-tooltip/circle-tooltip.component.html
packages/uhk-web/src/app/components/circle-tooltip/circle-tooltip.component.ts
packages/uhk-web/src/app/components/layers/layers.component.html
packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command.component.html
packages/uhk-web/src/app/components/macro/action-editor/tab/command/macro-command.component.scss
packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.html
packages/uhk-web/src/app/components/popover/popover.component.html
packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.html
packages/uhk-web/src/app/components/popover/tab/keypress/keypress-tab.component.scss
packages/uhk-web/src/app/components/slider-wrapper/slider-wrapper.component.html
packages/uhk-web/src/app/components/slider-wrapper/slider-wrapper.component.scss
packages/uhk-web/src/styles/_global.scss

closes: #2260
This PR replaces all old circle icon with tooltip with the `circle-tooltip` component. This component tries to show the tooltip at bottom of the icon but if there is not enough place then render at the top of the icon. The `circle-tooltip` also supports to set custom tooltip width so we don't need custom css classes.

fix: tooltip positioning

---

packages/uhk-web/src/app/components/device/firmware/device-firmware.component.ts

closes #2259
The firmware upgrade can be started from other places than the firmware page. In this case the upgrade type field did not have value.

fix: set default value of upgradeType on firmware page

---

packages/uhk-web/src/app/components/device/typing-behaviour-page/typing-behaviour-page.html

fix: "Double tap to lock layer timeout" tooltip on the typing behaviour page

---

packages/uhk-agent/src/services/smart-macro-doc.service.ts

This could happen when user starts Agent before connect an UHK to the computer.

fix: skip download firmware documentation if git info missing

---

packages/uhk-web/src/app/components/macro/edit/macro-edit.component.html
packages/uhk-web/src/app/components/macro/edit/macro-edit.component.ts
packages/uhk-web/src/app/components/macro/item/macro-item.component.html
packages/uhk-web/src/app/components/macro/item/macro-item.component.scss
packages/uhk-web/src/app/components/macro/item/macro-item.component.ts
packages/uhk-web/src/app/components/macro/list/macro-list.component.html
packages/uhk-web/src/app/components/macro/list/macro-list.component.ts
packages/uhk-web/src/app/components/popover/widgets/icon/icon.component.ts
packages/uhk-web/src/app/models/duplicate-macro-action-payload.ts
packages/uhk-web/src/app/models/index.ts
packages/uhk-web/src/app/store/actions/macro.ts
packages/uhk-web/src/app/store/effects/user-config.ts
packages/uhk-web/src/app/store/reducers/user-configuration.ts

closes #2274
merge the #2295 PR first to be able to test macro action cloning

feat: duplicate macro item

---

packages/uhk-web/src/app/components/device/led-settings/led-settings.component.html
packages/uhk-web/src/app/components/device/led-settings/led-settings.component.ts
packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.html
packages/uhk-web/src/app/components/device/mouse-speed/mouse-speed.component.ts

In the #1707 PR we removed the visibility of the pips from the sliders, but we did not deleted the pips properties. In the #2275 we have to use pips, so in this PR I just remove the old unused pip definitions

chore: remove unused noUiSlider pips

---

packages/uhk-web/src/app/components/user-configuration-history/user-configuration-history.component.html

Reproduction
- connect a new device to the computer or delete the device specific user config directory
- open Agent
- navigate to the user configuration page
- select the "new" device tab
- the old user configs should visible

fix: show legacy user config history when new device connected

---

packages/uhk-common/src/config-serializer/config-items/user-configuration.ts

fix: serialisation of "Trigger safety margin" in secondary roles of typing behavior

---

scripts/release.js

fixes "Please specify notarization Team ID in the `APPLE_TEAM_ID` env var instead of `notarize.teamId`" error

chore: set APPLE_TEAM_ID environment variable

---

package-lock.json
package.json

closes #2477. Tested on the 3 major OS
Maybe the https://github.com/electron/electron/pull/44998 PR will fix the issue

chore: downgrade electron 33.3.0 => 33.2.1 to fix mac context-menu event

---

packages/uhk-web/src/app/services/key-action-drag-and-drop.service.ts

fix: drag and drop of keyaction

---

packages/uhk-common/src/models/device-connection-state.ts
packages/uhk-common/src/util/index.ts
packages/uhk-common/src/util/is-bit-set.ts
packages/uhk-usb/src/models/device-state.ts
packages/uhk-usb/src/uhk-hid-device.ts
packages/uhk-web/src/app/app.component.html
packages/uhk-web/src/app/app.component.scss
packages/uhk-web/src/app/app.component.ts
packages/uhk-web/src/app/components/device/ble-pairing-panel/ble-pairing-panel.component.html
packages/uhk-web/src/app/components/device/ble-pairing-panel/ble-pairing-panel.component.scss
packages/uhk-web/src/app/components/device/ble-pairing-panel/ble-pairing-panel.component.ts
packages/uhk-web/src/app/components/svg/keyboard/svg-keyboard.component.html
packages/uhk-web/src/app/models/ble-adding-state.ts
packages/uhk-web/src/app/models/index.ts
packages/uhk-web/src/app/shared.module.ts
packages/uhk-web/src/app/store/actions/user-config.ts
packages/uhk-web/src/app/store/effects/device.ts
packages/uhk-web/src/app/store/effects/user-config.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/user-configuration.ts
packages/usb/get-device-state.ts

Agent part of the https://github.com/UltimateHackingKeyboard/firmware/issues/980
closes #2451

feat: BLE HID pairing

---

packages/uhk-agent/src/util/command-line.ts
packages/uhk-usb/src/utils/assert-command-line-options.ts
packages/uhk-usb/src/utils/device-vid-pid-interface-filter.ts
packages/usb/src/command-line.ts

chore: make usb-interface command line argument optional

---

packages/uhk-agent/src/services/device.service.ts
packages/uhk-common/src/models/device-module-record.ts
packages/uhk-common/src/models/device-version-information.ts
packages/uhk-common/src/models/firmware-version-info.ts
packages/uhk-common/src/models/module-version-info.ts
packages/uhk-common/src/models/uhk-module-ids.ts
packages/uhk-usb/src/constants.ts
packages/uhk-usb/src/uhk-hid-device.ts
packages/uhk-usb/src/uhk-operations.ts
packages/uhk-web/src/app/store/reducers/firmware-upgrade.reducer.ts

first part of the #2507
Drop Dongle state caching. I will refactor in other PR

fix: compare checksum of UHK80 and dongle devices

---

packages/uhk-web/package-lock.json
packages/uhk-web/package.json

monaco-editor 0.51.0+ does not load. It has amd module loading issue. After the angular upgrade have to check again, because maybe we could switch to esm module

chore: bump monaco-editor 0.48.0 => 0.50.0

---

packages/uhk-agent/src/services/device.service.ts
packages/uhk-common/src/models/ipc-response.ts
packages/uhk-common/src/util/ipcEvents.ts
packages/uhk-usb/src/constants.ts
packages/uhk-usb/src/uhk-operations.ts
packages/uhk-web/src/app/components/device/host-connections/host-connections.component.html
packages/uhk-web/src/app/components/device/host-connections/host-connections.component.ts
packages/uhk-web/src/app/models/erase-ble-settings-button-state.ts
packages/uhk-web/src/app/models/index.ts
packages/uhk-web/src/app/services/device-renderer.service.ts
packages/uhk-web/src/app/store/actions/device.ts
packages/uhk-web/src/app/store/effects/device.ts
packages/uhk-web/src/app/store/effects/user-config.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/device.ts
packages/uhk-web/src/app/store/reducers/dongle-pairing.reducer.ts

closes #2493
firmware pair https://github.com/UltimateHackingKeyboard/firmware/pull/1147 PR

feat: delete device pairings

---

packages/uhk-common/src/config-serializer/config-items/host-connection.ts
packages/uhk-common/src/config-serializer/config-items/serialisation-info.ts
packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
packages/uhk-web/src/app/services/user-config-80.json
packages/uhk-web/src/app/store/reducers/dongle-pairing.reducer.ts

closes #2562
User config version changed from 8.3.0 => 8.3.1. This PR does not change it in the root `package.json` because we don't have firmware with `8.3.1` user config. Maybe this issue will be handled with [#2432](https://github.com/UltimateHackingKeyboard/agent/issues/2432)
Also fixes a bug when the 2nd dongle is paired in a row then showed `Dongle paired` instead of `A dongle is detected. Pair it with this keyboard.`

fix: BLE address display

---

packages/uhk-common/src/config-serializer/config-items/host-connection.ts
packages/uhk-common/src/config-serializer/config-items/user-configuration.ts
packages/uhk-web/src/app/store/reducers/user-configuration.ts

feat: when reordering connections, change the ids of the related device actions accordingly

---

packages/uhk-agent/src/package.json

We bundle `electron-settings` we don't need to install it

chore: remove electron-settings from the electron bundle package.json

---

packages/uhk-web/src/app/components/keyboard/slider/keyboard-slider.component.scss

It is a quick fix of the https://github.com/UltimateHackingKeyboard/agent/issues/2424#issuecomment-2764764330 .
The "phantom" key is the key from the prev/next layer. This PR is the fastest solution that I could provide now. I don't know how much effort would we like to put in it.

fix: visibility of the corner of the next/prev layer when screen is very small

---

packages/uhk-agent/src/services/device.service.ts
packages/uhk-agent/src/util/backup-user-configuration.ts
packages/uhk-common/src/util/helpers.ts
packages/uhk-common/src/util/user-configuration-history-helpers.ts
packages/uhk-web/src/app/models/index.ts
packages/uhk-web/src/app/models/newer-user-configuration.ts
packages/uhk-web/src/app/pages/update-agent.page.ts
packages/uhk-web/src/app/services/default-user-configuration.service.ts
packages/uhk-web/src/app/store/actions/user-config.ts
packages/uhk-web/src/app/store/effects/device.ts
packages/uhk-web/src/app/store/effects/user-config.ts
packages/uhk-web/src/app/store/index.ts
packages/uhk-web/src/app/store/reducers/device.ts
packages/uhk-web/src/app/store/reducers/user-configuration.ts

Offer to load or reset user configuration when keyboard contains newer user configuration that Agent support
Based on #2576 but we don't downgrade the firmware, because it not necessary. closes #2576
Also implements the `If flashed user config version is <= agent's user config version, it should load the config` from #2432
To test the `restore the default configuration`
-  change the `userConfigVersion` version to `9.98.0` in the root package.json
To test the `restore the latest configuration available`:
- change the `userConfigVersion` version to `9.98.0` in the root package.json
- change on of the following if conditions 
- `if (!shouldUpgradeAgent(config.getSemanticVersion(), false)) {` => `if (true) {` in `packages/uhk-agent/src/util/backup-user-configuration.ts` line 37
- `if …

feat: load earlier / reset user configuration that Agen support

---

packages/uhk-web/src/app/util/status-buffer-parser.ts

The https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v14.2.0 changed the syntax of the macro command error. 
```log
> 4 | ifHold final holduKey 1 <--- before
] 4 | ifHold final holduKey 1 <--- after
```
This PR makes prevent the crashes of the Agent if can't parse the macro line informaition

fix: prevent crash when can't parse macro command line from status buffer

---

packages/uhk-web/src/app/components/keymap/edit/keymap-edit.component.ts

closes [#2651](https://github.com/UltimateHackingKeyboard/agent/issues/2651)

fix: decode keymap abbreviation url parameter

---

packages/uhk-web/src/app/store/reducers/device.ts

Can save the user configuration when opening the web demo with default (`/#`) url

fix: initialise the `connectedDevice` of device store
